- Lucy/Weekly Contest 397/3146_Permutation_Difference_between_Two_Strings.js
- Lucy/Weekly Contest 397/3147_Taking_Maximum_Energy_From_the_Mystic_Dungeon.js
- Lucy/Weekly Contest 397/3148_Maximum_Difference_Score_in_a_Grid.js
> Revert "Revert "[Weekly Contest 397] [Lucy] 1주차 3문제 풀이""

- Gombang/Weekly Contest 398/3151_Special_Array_I.cs
- Gombang/Weekly Contest 398/3152_Special_Array_II.cs
Q. Special Array I
---
- 해당 문제는 단순하게 for문을 돌리면서 2로 나눈 나머지가 같은 경우 (짝, 짝) 혹은 (홀, 홀)이 나왔다는 의미이므로 false로 반환, 그렇지 않으면 true를 반환하도록 진행하였습니다. 큰 어려움 없이 진행하게 되었습니다.
Q. Special Array II
---
- 이 문제는, 요구사항에 대해서는 이전 비슷한 문제인 것 같아 그대로 풀이를 하려고 하였으나, Time Limit Excceeded에러가 발생하였습니다. 다른 방식으로 문제를 풀어야겠다는 생각을 해서 어떤 경우가 있을지 고민하다가, nums를 쭉 순회하면서 (홀, 짝, 홀 짝, ...) 이렇게 숫자들이 나열되어 있다면 Speical하므로 계속 동일한 값을 넣어주다가, Speical하지 않은(홀, 홀 또는 짝, 짝) 경우가 나올 때 기존에 넣어주던 값에서 +1을 증가시켜서 넣어주는 방식으로 진행하였습니다. 이 문제를 풀면서 느낀점은 제약 조건(?)을 미리 생각해보았다면, 반복문을 중복해서 돌려야 하는 풀이 방법은 굳이 하지 않았어도 되지 않았을까? 하는 생각이 들었습니다.
> [Weekly Contest 398] [Gombang] 2주차 2문제 풀이

- Lucy/Weekly Contest 398/3151_Special_Array_1.js
- Lucy/Weekly Contest 398/3152_Special_Array_2.js
- Lucy/Weekly Contest 398/3153_Sum_of_Digit_Differences_of_All_Pairs.js
- topic: Array
- Difficulty: Easy
- 회고
- for문을 사용하여 각 배열의 요소를 순차적으로 순회하며 parity의 값이 연속으로 동일한지 동일하지 않는지 찾는 문제였는데 한 번이라도 연속으로 동일하면 그 배열은 special한 Array가 아닌게 되어 생각보다 문제를 푸는게 쉽게 느껴졌다
- topic: Prefix Sum
- Difficulty: Medium
- 회고
- 첫 번째 문제와 비슷한 문제여서 이해하기는 쉬워서 처음에는 첫 번째 문제의 풀이를 가져와서 풀었더니 시간 초과가 발생했다... 어떻게 하면 시간 초과가 나지 않게 문제를 해결할 수 있을까 고민하다가 답이 나오지 않아서 Solution Tab에서 답을 찾아 문제를 풀 수 있었다. Solution Tab에서 이진 탐색이나 Prefix Sum에 대해서 풀이를 한 것을 봤는데 Prefix Sum 알고리즘으로 풀이를 한 것이 이해가 더 잘되어 해당 알고리즘으로 풀이를 했다. 처음에 Prefix Sum 알고리즘 solution을 봤을 때, 이해가 안돼서 Chat GPT에게 이해를 시켜달라고 부탁을 했더니 잘 알려줘서 나만의 코드로 풀이를 할 수 있었다.
- Topic: Array, Hash Table, Math, Counting
- Difficulty: Medium
- 회고
- 문제를 읽었을 때, 이해가 잘 안됐다. 예제를 보고 이해가 됐지만 어떻게 풀어야할지 감이 잡히지 않았다. 그래서 Hint 1, 2, 3를 다 봤다. 그래도 감이 잡히지 않았다. 그러면 Solution Tab으로 가서 다른 사람들은 어떻게 풀이를 …
> [Weekly contest 398] [Lucy] 2주차 3문제 풀이

- Seori/Weekly Contest 398/3151. Special Array I.py
- Seori/Weekly Contest 398/3152. Special Array II.py
- Seori/Weekly Contest 398/3153. Sum of Digit Differences of All Pairs.py
**3151. Special Array I**
---
- Special의 규칙을 찾는 간단한 문제. `i`와 `i+1`의 숫자를 더해서 홀수이면 special하다는 규칙을 찾아 해결했다.
**3152. Special Array II**
---
- 3151번 문제에서 찾은 규칙을 활용해서 금방 해결할 줄 알았지만 시간복잡도에서 애를 먹었다.
- `nums`의 길이가 $10^5$였기 때문에 2중 for문을 사용할 수 없었다.
- 따라서 `queries`에서 주어지는 `index`를 탐색할 때 이진탐색 알고리즘을 사용하여 해결했다.
- python에서 이진탐색 시 유용하게 사용할 수 있는 `bisect`의 사용법을 익혔다. 
**3153. Sum of Digit Differences of All Pairs**
---
- 도저히 유형과 풀이 방법을 알 수 없어 유튜브로 공부했다.
- 참고했던 풀이법은 `dp`같은 풀이였다. 규칙은 다음과 같다.
1. `nums`의 숫자들을 순서대로 탐색한다.
2. 일, 십, 백...등등 `i`의자리수에 `k`라는 숫자가 몇 번 나왔는지를 `counter`에 기록한다.
3. `n`번째 숫자를 탐색하면서 `n - counter[i][k]`를 계산해주는 것이 정답의 핵심이다.
> [Weekly Contest 398] [Seori] 2주차 3문제 풀이

- Lucy/Weekly Contest 399/3162_Find_the_Number_of_Good_Pairs_1.js
- Lucy/Weekly Contest 399/3163_String_Compression_3.js
- Lucy/Weekly Contest 399/3164_Find_the_Number_of_Good_Pairs_2.js
- topic: Array
- Difficulty: Easy
- 회고
- Constraints가 그리 빡빡하지 않아서 이중 for문으로 빠르게 풀 수 있었다.
- topic: String
- Difficulty: Medium
- 회고
- String 문제를 풀 때, String 인스턴스 메서드를 사용하는 경우 Time Limit Exceeded 가 뜨는 경우가 종종 있다. 다음부터는 String 주제일 경우 인스턴스 메서드를 쓰지 않고 문제를 풀도록 해야겠다.
- topic: Array, Hash Table
- Difficulty: Medium
- 회고
- Find the Number of Good Pairs 1 문제와 동일하지만 Constraints가 좀 더 난이도가 있는 문제였다. 그래서 시간복잡도를 어떻게 해야만 할까 고민했지만...방법이 떠오르지 않아서 Chat GPT에게 물어봤다. Chat GPT가 알려준 방법은 아래와 같다.
- 각 nums2[j] * k의 값을 미리 계산하고, 그 값을 key로 사용하여 해당 값의 빈도를 저장하는 해시맵을 만듭니다. nums1의 각 원소에 대해 nums1[i]가 해시맵의 key에 존재하는지 확인하고, 존재하면 그 빈도를 결과에 더합니다.
- 하지만 위 방법으로 풀이를 했을 때, `Time Limit Exceeded`가 떴다..!
- 그래서 `Discuss` 탭에서 풀이를 보고 나만의 코드로 다시 풀이를 진행했다. Discuss에서 본 풀이는 map을 생성하여 그 map에 `nums2[j] * k` 를 key값으로 하고 그 key 값의 빈도수를 value 값으로 …
> [Weekly contest 399] [Lucy] 3주차 3문제 풀이

- Gombang/Weekly Contest 399/3162_Find_the_Number_of_Good_Pairs_I.cs
- Gombang/Weekly Contest 399/3163_String_Compression_III.cs
- Gombang/Weekly Contest 399/3164_Find_the_Number_of_Good_Pairs_II.cs
Q. Find the Number of Good Pairs 1
---
- 해당 문제는 어렵지 않게 요구사항 그대로 이중 포문을 이용하여 풀이하였습니다.
Q. String Compression 3
---
- 기존에 string을 사용해서 '+=' 연산으로 진행하였었는데, 이때에는 Time Limit Exceeded 에러가 나왔었다.
string의 '+=' 연산에 대해서 알아본 결과 문자열을 결합할 때마다 새로운 string 객체를 생성하고 기존 문자열의 내용을 복사하는데, 문자열의 길이가 길어질수록 메모리 할당과 복사 작업이 많아져 성능 저하가 발생하게 된다는 내용을 알게 되었다.
- 다른 방식을 알아보니, C#에서는 StringBuilder라는 것을 이용하면 많은 양의 문자열을 조작해야 할 때 성능적으로 큰 이점이 많다고 하여 사용해보니 해결되었다. StringBuilder방식은 내부적으로 배열을 사용하여 문자열을 저장하는 방식인데, 배열이 가득차게 되면 배열 크기를 두 배로 늘리면서 새로운 배열을 할당하고 복사하는 방식이다. 배열 크기를 두 배로 늘리는 방식 덕분에 배열 확장은 로그 시간 복잡도를 가지게 되어, 새로운 공간 할당에 대해서 좋은 성능을 갖게 된다.
- 문제를 풀면서 하나 재미있었던 점은, Solution에서 C++의 풀이 방법을 확인해보니 알고리즘은 거의 유사하였지만 string의 '+=' 연산으로도 통과가 되는 것을 확인하였다. 그래서 C++의 string에 대해서 확인해본 결과, C#의 StringBuilder와 비슷한 방식으로 동작한다는 것을 알게 되었다(내부적으로 동적 배열을 …
> [Weekly contest 399] [Gombang] 3주차 3문제 풀이.

- Seori/Weekly Contest 399/3162. Find the Number of Good Pairs I.py
- Seori/Weekly Contest 399/3163. String Compression III.py
- Seori/Weekly Contest 399/3164. Find the Number of Good Pairs II.py
**3162. Find the Number of Good Pairs I**
---
- Good Pairs의 규칙을 찾는 간단한 문제. `nums1`의 원소와 `num2`의 원소에 `k`를 곱한 값을 전부 비교했다.
**3163. String Compression III**
---
- 제목을 보아하니 유형화되었을 법한 String Compression 문제. 앞에서부터 차례대로 같은 문자가 몇 개 나왔는지 세는 문제였다.
- `cnt` 변수를 사용해서 문제 조건에 충실하게 풀었다.
- `cnt`라는 정수형 값을 `comp`에 더할 때 문자열 처리 해주는 부분이 귀찮았다.
**3164. Find the Number of Good Pairs II**
---
- 3162번의 풀이를 그대로 차용하면 당연히 O($n^2$)으로 안될 것이라서 O($n$) 풀이를 구상하였다.
- 주석으로 남겨둔 for문이 첫 풀이였으나 극악무도한 반례에 막혀 시간초과가 났다.
- 모범답안을 참고하여 Counter로 돌파했다.
- 첫 풀이에 비해 nums2 안에서 반복되는 값들을 제거해주기 때문에 시간초과를 피할 수 있었다.
> [Weekly Contest 399] [Seori] 3주차 3문제 풀이

- Lucy/Weekly Contest 400/3168_Minimum_Number_of_Chairs_in_a_Waiting_Room.js
- Lucy/Weekly Contest 400/3169_Count_Days_Without_Meetings.js
- Lucy/Weekly Contest 400/3170_Lexicographically_Minimum_String_After_Removing_Stars.js
- topic: String
- difficulty:  EASY
- 회고
- Hint를 보고 방에서 최대한 많은 사람이 기다렸던 경우를 max라는 변수에 저장하여 풀어낼 수 있었다. 문제를 어떻게 풀어야 할지 판단하는게 아직은 좀 어려워서 이런 문제를 많이 풀어보는 연습이 필요한 것 같다.
- topic: ?
- difficulty: MEDIUM
- 회고
- Discuss Tab에서 Line Sweep Algorithm 알고리즘을 활용하라는 힌트를 얻어서 그 알고리즘을 Chat GPT로 공부하며 풀어낼 수 있었다. 새로운 알고리즘을 알게돼서 재밌었고 나중에 이 알고리즘을 사용해서 풀어야 하는 문제들을 더 찾아내서 풀어봐야겠다.
- Line Sweep Algorithm 이란?
- 여러 이벤트가 시간 축 상에서 발생하는 경우를 효율적으로 처리하는 알고리즘
- 이 알고리즘은 주로 회의 일정, 선분 겹침 문제, 직사각형 교차 등의 문제에서 많이 사용됨
- topic: Hash Table, String, Stack, Greedy, Heap(Priority Queue)
- difficulty: MEDIUM
- 회고
- topic 에서 Hash Table 을 보고 "*" 와 일반 문자를 각각 starArr, nonStarArr에 index와 value 라는 key를 갖는 object들을 넣고 starArr를 for문으로 순회하면서 연산을 수행하도록 문제를 풀어봤다. 하지만 시간 초과가 났다.
- Discuss에서 가장 상단에 올라와 있는 글을 보고 거기서 PriorityQueue를 사용하여 heap을 구현해서 문제를 …
> [Weekly contest 400] [Lucy] 4주차 3문제 풀이

- Seori/Weekly Contest 400/3168. Minimum Number of Chairs in a Waiting Room.py
- Seori/Weekly Contest 400/3169. Count Days Without Meetings.py
- Seori/Weekly Contest 400/3170. Lexicographically Minimum String After Removing Stars.py
**3168. Minimum Number of Chairs in a Waiting Room**
---
- 주어진 문자열에 규칙을 적용하는 문제. 간단하게 해결할 수 있었다.
**3169. Count Days Without Meetings**
---
- 이전에 나왔던 `Prefix Sum` 문제를 떠올려 풀어보았지만, `days`의 길이가 $10^9$으로 메모리 초과가 발생했다.
- 주어지는 `meetings`를 먼저 정렬하고서 풀이하는 게 문제의 핵심이었다고 생각한다.
- 정답자 중 가장 끝자락에 걸쳤다. 중복되는 회의들을 스마트하게 줄이는 방법을 공부해야겠다.
**3170. Lexicographically Minimum String After Removing Stars**
---
- 효율적으로 푸는 방법을 고민하던 중, 디스커션에서 O($n^2$)으로 풀린다길래 착수해보았다. 이왜진?
- 하지만 역시나 소요시간 `6291ms`로 가장 꼴찌다. 모범답안으로 더 공부해서 다시 풀어야겠다.
> [Weekly Contest 400] [Seori] 4주차 3문제 풀이

- Gombang/Weekly Contest 400/3168_Minimum_Number_of_Chairs_in_a_Waiting_Room.cs
- Gombang/Weekly Contest 400/3169_Count_Days_Without_Meetings.cs
Q. Minimum Number of Chairs in a Waiting Room
---
- 해당 문제는 최소한의 의자 개수를 구하는 문제였는데 'E'이면 ++를, 'L'이면 --를 진행하여, 결과값의 최대값을 구하기만 하면 되는 문제로 파악하여 다른 문제에 비해 쉽게 진행할 수 있었습니다.
Q. Count Days Without Meetings
---
- 해당 문제는 처음에 비효율적인 방식으로 문제를 풀게 되어 힌트를 보고 다시 진행하였습니다.
- 시작일을 기준으로 오름차순 정렬을 하게 되면, 중간에 겹치는 구간에 대해서는 간단한 수식을 통해 쉽게 문제가 풀린다는 것을 알게되어 해당 방식으로 진행하였습니다.
- 앞으로 '겹치는 구간'에 대한 문제를 만나게 된다면 정렬을 이용해서 수식으로 접근할 수 있는지를 파악해보는 연습을 해봐야겠다는 생각을 하게 되었습니다.
> [Weekly contest 400] [Gombang] 4주차 2문제 풀이

- Lucy/Weekly Contest 401/3178_Find_the_Child_Who_Has_the_Ball_After_K_Seconds.js
- Lucy/Weekly Contest 401/3179_Find_the_N-th_Value_After_K_Seconds.js
- Lucy/Weekly Contest 401/3180_Maximum_Total_Reward_Using_Operations_I.js
- README.md
- topic: Math, Simulation
- 회고
- 수학 공식을 찾아서 풀어내려 했으나 공식을 찾지 못하고 반복문을 사용하여 코드를 작성하는 게 자신 또는 타인이 보기에 이해 하기 쉬운 코드라 생각되어 for문을 사용해서 문제를 풀이했습니다.
- topic: Array, Math, Simulation, Combinatorics, Prefix Sum
- 회고
- 처음에 `Since the answer may be very large, return it modulo 10^9 + 7.` 문장을 무시하고 구현했을 때, Wrong Answer라는 결과를 받았다. modulo롤 추가해주고 난 후에는 문제를 해결할 수 있었습니다. 문제에 나온 문장은 하나도 그냥 있는게 아니니 어떤 문장도 무시하지 말아야겠습니다.
- topic: Array, Dynamic Programming
- 회고
- DP 문제여서 점화식을 고민해봤지만 모르겠어서 Discuss 탭에서 다른 사람의 풀이를 찾아봤습니다. 다른 사람의 풀이를 통해 구현해봤지만 처음에는 Time Limit Exceeded로 문제를 풀이하지 못했습니다. 또 다른 풀이를 보니 현재 풀이와 거의 동일한데 dp 배열의 길이만 2001에서 n으로 달랐습니다. 시간 복잡도는 동일하고 공간 복잡도만 다를 뿐인데 2001일 경우에는 왜 통과가 되지 않는지 이유를 모르겠어서 Chat GPT에 물어봤지만 시간복잡도가 다르지 않다는 대답만 들었습니다. 해당 부분은 조금 더 …
> [Weekly contest 401] [Lucy] 5주차 3문제 풀이

- Seori/Weekly Contest 401/3178. Find the Child Who Has the Ball After K Seconds.py
- Seori/Weekly Contest 401/3179. Find the N-th Value After K Seconds.py
**3178. Find the Child Who Has the Ball After K Seconds**
---
- 간단하게 정방향, 역방향일 때의 수학적 규칙을 찾아 풀어낼 수 있었다.
**3179. Find the N-th Value After K Seconds**
---
- 바로 점화식이 떠올라 DP로 접근하였다.
- 종이에 파스칼 삼각형 형태로 풀어보려다가, 매우 간단한 점화식으로 표현할 수 있다는 점을 깨달았다. 구하고자 하는 수`cur[j]`는 위의 값`prev[j]`과 왼쪽 값`cur[j-1]`의 합인 형태이다.
- 풀이는 이래봬도 고민하고 푸는 데 꽤 오래 걸렸다.
> [Weekly Contest 401] [Seori] 5주차 2문제 풀이

- Gombang/Weekly Contest 400/3169_Count_Days_Without_Meetings.cs
- Gombang/Weekly Contest 401/3178_Find_the_Child_Who_Has_the_Ball_After_K_Seconds.cs
- Gombang/Weekly Contest 401/3179_Find_the_N-th_Value_After_K_Seconds.cs
Q. Find the Child Who Has the Ball After K Seconds
---
- 문제에서 풀이를 진행하는 방식대로 direction을 이용하여 반복문을 통해 문제를 해결하였다. 크게 어려움은 없었던 문제였다.
Q. Find the N-th Value After K Seconds
---
- 이 문제 또한 점화식에 대해서는 큰 어려움은 없었던 문제였다. 매초마다 누적된 합을 배열에 값을 넣어줌으로써 문제를 해결할 수 있었다.
> [Weekly contest 401] [Gombang] 5주차 2문제 풀이

- Lucy/Weekly Contest 402/3184_Count_Pairs_That_Form_a_Complete_Day_I.js
- Lucy/Weekly Contest 402/3185_Count_Pairs_That_Form_a_Complete_Day_II.js
- Lucy/Weekly Contest 402/3186_Maximum_Total_Damage_With_Spell_Casting.js
- topic: Array, Counting, Hash Table
- 회고
- 2중 for문을 사용해도 되는 제약조건이어서 2중 for문으로 배열을 순회하면서 24로 나누어지는 쌍을 찾아 count 하는 식으로 풀었습니다.
- 이제 난이도가 Easy한 문제는 금방 풀어내는 거 같아서 자신감이 조금 붙었다고 생각합니다. 이제 Medium도 Easy 문제 풀어내듯 풀 수 있었으면 좋겠습니다.
- topic: Array, Counting, Hash Table
- 회고
- Hint를 봐도 문제 해결 법을 찾지 못해 Chat GPT의 힘을 빌려서 풀이했다.
- 제약 사항으로 배열의 길이가 길어지거나 요소의 값이 커지면 시간 복잡도에서 걸리는데 연습이 많이 필요한 것 같다. 시간 복잡도가 걸리는 문제는 한 번씩 다시 풀어봐야겠다.
- topic: Array, Hash Table, Two Pointers, Binary Search, Dynamic Programming, Sorting, Counting
- 회고
- DP 문제는 아직 어렵다. DP 배열을 채울 때, 어떤 점화식을 사용해야 하는지 감을 잡지 못했다...연습이 더 필요한 것 같다.
- 다른 사람의 풀이를 보고 풀어보는데도 이해하는데 꽤 걸렸다.
- 이번 문제도 1~2일 지나고 다시 풀어봐야겠다.
> [Weekly contest 402] [Lucy] 6주차 3문제 풀이

- Gombang/Weekly Contest 402/3184_Count_Pairs_That_Form_a_Complete_Day_I.cs
- Gombang/Weekly Contest 402/3185_Count_Pairs_That_Form_a_Complete_Day_II.cs
- Gombang/Weekly Contest 402/3186_Maximum_Total_Damage_With_Spell_Casting.cs
Q. Count Pairs That Form a Complete Day 1
---
- 해당 문제는 두 요소를 더했을 때, 24로 나누어 떨어지는지만을 체크하면 되는 문제여서 2중 포문을 이용해 구현하였습니다. 
Q. Count Pairs That Form a Complete Day 2
---
- 해당 문제는 1번 문제의 풀이법을 그대로 사용할 경우 타임 에러가 나게 되어 다른 풀이법으로 진행해야 했습니다. 혼자서는 해결하지 못하여 솔루션 풀이를 보고 이해한 후 진행하였습니다.
- 두 요소를 직접 더하는 방식이 아닌 24로 나눈 나머지 값으로 요소들을 대체하여, 해당 값에서 어떤 값을 더해야 24라는 완벽한 날이 되는지를 체크하는 방식으로 진행하였습니다.
- 생각보다 코드는 짧았지만, 이런 풀이법도 있구나라는 생각을 갖게 된 문제였습니다.
Q. Maximum Total Damage With Spell Casting
---
- 마지막 문제는 dp문제라는 것은 눈치챘으나, 어떤 식을 세워야 하는지에 대해서 많은 어려움이 있었습니다. 이 문제 또한 솔루션을 보고 풀이를 진행하였습니다.
- dp문제는 어떤식으로 풀어야 하는지 계속 막히는 것 같다. 연습이 더욱 필요할 것 같습니다.
> [Weekly contest 402] [Gombang] 6주차 3문제 풀이

- Seori/Weekly Contest 403/3194. Minimum Average of Smallest and Largest Elements.py
- Seori/Weekly Contest 403/3195. Find the Minimum Area to Cover All Ones I.py
- Seori/Weekly Contest 403/3196. Maximize Total Cost of Alternating Subarrays.py
**3194. Minimum Average of Smallest and Largest Elements**
---
- 정렬을 활용하여 인덱스로 `max`, `min`값을 구하도록 구성하여 풀이하였다.
**3195. Find the Minimum Area to Cover All Ones I**
---
- 직사각형의 넓이를 구하려면 `(left, top)`, `(right, bottom)` 좌표값이 필요하다.
- 2차원 배열 특성상 행 순서로는 인덱스 접근하기 쉬우므로 `top`, `bottom`을 먼저 구하고
- 파이썬의 `zip` 메서드를 사용하여 배열을 90도 꺾어서, 마찬가지로 `left`, `right`값을 구하였다.
**3196. Maximize Total Cost of Alternating Subarrays**
---
- 지문을 이해하기 힘들어서 반례를 통해 점점 감을 찾았던 문제였다.
- 정리하자면 배열에서 연속하지 않게 `-1`을 곱해서 구할 수 있는 최대 `sum`값을 찾는 것이었다.
- `i-1`번째 수에 `-1`을 곱했다면 `i`번째 수는 더할 수 밖에 없다는 2지 선다를 `dp[0]`, `dp[1]`로 구성해서 풀었다.
1. `dp[0][i]`에는 `i-1`번까지의 최대값에 `i`번째 수를 더한 값
2. `dp[1][i]`에는 `i-1`번째에서 더했을 경우의 최대값`dp[0][i-1]`에 `i`번째 수를 뺀 값을 기록한다.
> [Weekly Contest 403] [Seori] 7주차 3문제 풀이

- Gombang/Weekly Contest 404/3200_Maximum_Height_of_a_Triangle.cs
- Gombang/Weekly Contest 404/3201_Find_the_Maximum_Length_of_Valid_Subsequence_I.cs
Q. Maximum Height of a Triangle
---
- 맨 처음에 문제를 딱 봤을때는 막막한 느낌이었는데, 어떻게 풀어야 될 지 계속 고민하다보니 홀수층( 필요 공 개수 : 1, 3, 5, ...)과 짝수층( 필요 공 개수 : 2, 4, 6, ... )에 대한 규칙을 통해 문제를 해결하게 되었습니다.
Q. Find the Maximum Length of Valid Subsequence I
---
- 해당 문제는 2로 나눈 나머지에 대한 문제이기 때문에, 짝수와 홀수가 번갈아 나오는 상황의 최대 길이와 짝수만 있을 때의 최대길이, 홀수만 있을 때의 최대길이 중 가장 큰 값이 해당 문제의 정답이 된다는 것을 알고 해당 방식으로 문제를 풀게 되었습니다.
> [Weekly Contest 404] [Gombang] 8주차 2문제 풀이

- Lucy/Weekly Contest 404/3200_Maximum_Height_of_a_Triangle.js
- Lucy/Weekly Contest 404/3201_Find_the_Maximum_Length_of_Valid_Subsequence_I.js
- Lucy/Weekly Contest 404/3202_Find_the_Maximum_Length_of_Valid_Subsequence_II.js
- topic: Array, Enumeration
- 회고
- 처음에는 색깔을 번갈아 가면서 row를 채워야 한다는 것을 자각하지 못하고 현재 row에서 red와 blue 모두 가능할 경우 다음 row에도 채울 수 있는 공이면 그 공을 row에 채우는 방식을 생각했는데 생각보다 답이 잘 나오지 않아서 관뒀습니다...!
- 그래서 `Hint`를 보고 어떤 방법으로 풀어야 할지 감을 잡았다. red 공과 blue 공 모두 최대 100개이니 시간복잡도가 제한적이진 않았다고 생각한다. 그래서 red가 top row에 채워진 경우와 blue가 top row에 채워진 경우에 나올 수 있는 height 값을 계산하여 2개의 height 값 중 더 큰 값을 반환하는 식으로 풀이했습니다.
- topic: Array, Dynamic Programming
- 회고
- 빈 dp 배열을 생성한 후, (dp[i - 2] + dp[i - 1]) % 2 의 값과 (dp[i-1] + nums 요소) % 2 의 값이 동일한 경우에만 dp 배열에 값을 push하는 식으로 풀이를 생각했습니다. 하지만...! 600번째 test case에서 Wrong Answer를 받았습니다.
- 그 다음에는 다른 사람의 풀이를 보고 공부를 해야겠다고 생각해서 Discuss 탭에서 간단한 풀이를 보고 풀어냈습니다. 같은 parity 인 경우 count한 값과 parity가 번갈아가면서 바뀌는 경우를 count한 값 중에서 더 큰 값을 return 하는 식으로 하여 풀이했습니다.
- …
> [Weekly contest 404] [Lucy] 8주차 3문제 풀이

- Seori/Weekly Contest 404/3200. Maximum Height of a Triangle.py
- Seori/Weekly Contest 404/3201. Find the Maximum Length of Valid Subsequence I.py
**3200. Maximum Height of a Triangle**
---
- 단순하게 while문으로 반복하는 풀이를 떠올렸고, 난이도가 낮은 문제라서 red, blue를 바꿔 두 번 적용해주면 되겠지 하고 작성했다.
**3201. Find the Maximum Length of Valid Subsequence I**
---
- 처음에는 차이가 `[0, 1, 0]`이나 `[1, 0, 1]`일 때와 같이 어떤 규칙을 찾으려고 했으나 실패하고 힌트를 참고했다.
- 나누는 숫자가 `2`이므로 3번째 문제에 비해서 훨씬 경우의 수가 간단해서 다음 풀이를 적용할 수 있었다.
> [Weekly Contest 404] [Seori] 8주차 2문제 풀이

- Lucy/Weekly Contest 405/3210_Find_the_Encrypted_String.js
- Lucy/Weekly Contest 405/3211_Generate_Binary_Strings_Without_Adjacent_Zeros.js
- Lucy/Weekly Contest 405/3212_Count_Submatrices_With_Equal_Frequency_of_X_and_Y.js
- topic: String
- 회고
- 처음에는 문제를 잘 이해를 못해서 s 문자열의 문자를 k번째에 위치로 바꾸는 거라고 생각했습니다. 하지만 문제를 다시 읽어보니 현재 문자에서 k번째 위치한 문자로 바꾸는 문제였습니다.
- k번째는 순환 방식으로 계산되기 때문에 `(i + k) % s.length` 라는 조건을 사용하여 k번째 문자를 찾아서 문자를 암호화하여 문제를 풀어낼 수 있었습니다.
- topic: String, Bit Manipulation, Recursion
- 회고
- 문제에서 주어진 Hint에서 backtracking과 recursion을 사용하라는 것을 보고 Chat GPT를 사용하여 Backtracking 알고리즘에 대해 공부를 했습니다. 한참을 생각하다가 답이 나오지 않아서 Chat GPT가 알려준 python 풀이를 javascript 풀이로 변경하여 풀어냈습니다.
- Backtracking 알고리즘이란? 가능한 모든 해를 탐색하는 과정에서, 현재의 상태에서 더 이상 유망하지 않다고 판단되는 경우에는 그 경로를 더 이상 탐색하지 않고 되돌아가는 방법입니다. `모든 가능한 조합을 생성하고 특정 조건을 만족하는 해를 찾는 데 유용`합니다.
- 주어진 길이 `n`의 이진 문자열을 생성할 때, 각 부분 문자열이 조건을 만족하는지 확인해야 합니다. 백트래킹을 사용하여 모든 문자열을 생성하면서 조건을 만족하지 않는 경우에는 더 이상 진행하지 않고 이전 상태로 돌아갑니다.
- 재귀함수 설계:
- 현재까지의 문자열을 인자로 …
> [Weekly contest 405] [Lucy] 9주차 3문제 풀이

- Gombang/Weekly Contest 405/3210_Find_the_Encrypted_String.cs
- Gombang/Weekly Contest 405/3211_Generate_Binary_Strings_Without_Adjacent_Zeros.cs
- Gombang/Weekly Contest 405/3212_Count_Submatrices_With_Equal_Frequency_of_X_and_Y.cs
Q. Find the Encrypted String
---
- 처음 문제를 보고나서 나머지 연산을 이용하면 좋을 것 같다는 생각이 들어, 나머지 연산을 이용하여 나머지 값에 해당하는 인덱스로 매칭하는 방식으로 진행하였습니다.
Q. Generate Binary Strings Without Adjacent Zeros
---
- 처음에 문제를 어떻게 풀어야 하나 고민하다가 잘 진행되지 않아서 힌트를 보고 문제를 풀게 되었습니다.
- 힌트를 보니 재귀적인 방식으로 알려주어서, 어떻게 문제를 재귀적으로 진행할 수 있는지를 보다보니 바로 문제 풀이를 캐치하게 되었습니다.
- 0이 연속으로 나올 수 없다고 하여, 0이 나오면 그 뒤에는 1이 붙도록 진행하였고, 1이 나오면 그 뒤에는 0, 1이 붙도록 재귀호출을 이용하여 진행하였습니다.
Q. Count Submatrices With Equal Frequency of X and Y
---
- 이 문제는 해결하지 못하여 솔루션을 보고 진행하였습니다. 솔루션에는 Prefix Sum 알고리즘을 이용하여 문제를 푸는 방식을 설명해주어서 해당 방식으로 진행하였습니다.
> [Weekly Contest 405] [Gombang] 9주차 3문제 풀이

- Lucy/Weekly Contest 407/3226_Number_of_Bit_Changes_to_Make_Two_Integers_Equal.js
- Lucy/Weekly Contest 407/3227_Vowels_Game_in_a_String.js
- Lucy/Weekly Contest 407/3228_Maximum_Number_of_Operations_to_Move_Ones_to_the_End.js
- topic: Bit Manipulation
- review
- 해당 문제는 파라미터로 주어진 `n`과 `k`를 이진수로 변환한 후에, 변환된 `n`을 변환된 `k`로 변경할 수 있는지 확인하고 변경된다면 bit가 변경되는 횟수를 반환하는 문제입니다.
- 주어진 파라미터 `n`과 `k`를 이진수로 변환하는 것부터 해야겠다고 생각했습니다. `toString()`메서드를 사용하여 10진수를 2진수로 변환할 수 있는 걸 알지만 다른 방법으로 시도해보고 싶어 인터넷에서 방법을 찾아보았습니다. `GeeksforGeeks`라는 페이지에서 비트 연산자를 사용한 방법을 찾을 수 있었습니다(https://www.geeksforgeeks.org/javascript-program-to-convert-a-number-to-binary/).
- 파라미터 `n`과 `k`를 2진수로 바꾼 후, 2진수 `n`을 순회하면서 bit가 1이고 2진수 `k`에서는 bit가 0인 경우에만 bit를 변환했습니다. 변환할 때마다 횟수를 카운트하는 로직을 넣어 몇 번 bit를 변화시켰는지 확인했습니다.
- 마지막으로 2진수 n을 변경한 결과가 2진수 k와 동일할 때에만 변경된 횟수를 반환하고 그 외에는 `-1`을 반환하도록 코드를 구현했습니다.
- topic: Math, String, Braineteaser, Game Theory
- review
- 문제를 한참을 들여다보고 이해할 수 있었습니다. 그리고 어찌 풀이해야 할지 감이 잡히지 않아서 LeetCode에서 제공해주는 …
> [Weekly contest 407] [Lucy] 11주차 3문제 풀이

- Seori/Weekly Contest 408/3232. Find if Digit Game Can Be Won.py
- Seori/Weekly Contest 408/3233. Find the Count of Numbers Which Are Not Special.py
- Seori/Weekly Contest 408/3234. Count the Number of Substrings With Dominant Ones.py
**3232. Find if Digit Game Can Be Won**
---
- 문제 조건에 맞게 1자리수와 2자리수를 구분하는 `if`문을 작성하고, `True/False`를 반환하여 해결하였다.
**3233. Find the Count of Numbers Which Are Not Special**
---
- `special number`는 소수의 제곱수이므로, `l`과 `r`의 제곱근의 범위 내에서 소수를 구하는 컨셉으로 접근했다.
- 에라토스테네스의 체와 집합 `set`를 이용하여 소수의 집합 `prime_set`을 구하고, 개수만 계산하여 해결했다.
**3234. Count the Number of Substrings With Dominant Ones**
---
- 880/881로 마지막 테스트케이스에서 `TLE` 발생...
- 시간초과 상관 없이 2중 `for`문으로 구성한 뒤 점점 최적화하는 방식으로 접근해보았다. `Discussion`도 참고했다.
- 경우의 수를 3가지로 나누고 발버둥쳐봤지만 결국에는 시간초과를 피할 수 없었다.
> [Weekly Contest 408] [Seori] 12주차 2문제 풀이

- Gombang/Weekly Contest 408/3232_Find_if_Digit_Game_Can_Be_Won.cs
- Gombang/Weekly Contest 408/3233_Find_the_Count_of_Numbers_Which_Are_Not_Special.cs
Q. Find if Digit Game Can Be Won
---
- 해당 문제는 단순하게, 일의자리 숫자의 누적 합과 두 자리 숫자의 누적합과 비교하여 서로 다르다면 앨리스의 승을 주는 방식으로 진행하였습니다.
Q. Find the Count of Numbers Which Are Not Special
---
- 문제를 보면서 스페셜한 숫자는 어떤 숫자인지를 확인해보니, 소수의 제곱으로 이루어져 있는 숫자라는 것을 파악할 수 있었습니다.
- 처음에는 직접 루프를 돌려가면서 해당 값이 소수의 제곱 값인지를 체크하는 방식으로 진행하였는데, TLE가 나오게 되어 소수를 구하는 다른 방법이 있는지를 찾아보았습니다. 그러던 중, 다량의 소수값을 체크할 때에는 에레스토테네스의 체를 이용하는 방식이 있다는 것을 알게되어 해당 방식을 사용하게 되었습니다. --> https://loosie.tistory.com/267
> [Weekly Contest 408] [Gombang] 12주차 2문제 풀이

- Lucy/Weekly Contest 408/3232_Find_if_Digit_Game_Can_Be_Won.js
- Lucy/Weekly Contest 408/3233_Find_the_Count_of_Numbers_Which_Are_Not_Special.js
- Lucy/Weekly Contest 408/3234_Count_the_Number_of_Substrings_With_Dominant_Ones.js
- topic: Array, Math
- review
- calcSingleDigitSum(), calcDoubleDigitSum() 함수에서 filter()메서드가 아닌 map() 메서드를 사용하여 원하는 값을 구해내지 못한 실수를 했습니다. 조건에 맞는 요소만 추려낼 때는 filter() 메서드를 사용하고, 배열 전체 요소를 변경할 때는 map() 메서드를 사용해야 하는 것을 잊지 말아야 겠습니다.
- topic: Array, Math, Number Theory
- review
- 처음에는 단순하게 `for문`을 사용하여 `본인을 포함하지 않은 약수의 갯수를 구하는` 함수 `cntProperDivisors()`를 선언하여 풀이를 했습니다.
- 하지만! `시간 복잡도` 때문에 통과하지 못했습니다.
- 그래서 `다른 사람의 풀이를 참고`하기로 했다. 다른 사람의 풀이에서는 `에라토스테네스의 체`로 소수를 구한 후, `소수의 제곱근이 약수인 경우를 체크`하여 특별한 숫자의 갯수를 구하여 특별하지 않은 숫자의 갯수를 구하는 풀이였다.
- 약수 문제가 나오면 무조건 `에라토스테네스의 체`를 생각해내야겠습니다.
- topic: String, Sliding Window, Enumeration
- review
- 처음에 관련 주제로 `Sliding Window`라는 알고리즘이 있기에 그걸 사용해서 문제 풀이를 시도했습니다.
- 처음보는 알고리즘의 유형이고 문제가 완벽하게 이해가 되지 않았기에 `Chat …
> [Weekly contest 408] [Lucy] 12주차 3문제 풀이

- Lucy/Weekly Contest 409/3242_Design_Neighbor_Sum_Service.js
- Lucy/Weekly Contest 409/3243_Shortest_Distance_After_Road_Addition_Queries_I.js
> 월요일까지 열심히 문제를 풀어보려 했으나...! `다익스트라 알고리즘`을 사용하여 최단 경로를 알아내야 하는 2번째 문제부터 시간이 많이 소요되어 3번째 문제는 손을 대지 못했습니다. 그리고 제가 꼭 참여하고 싶은 `프로젝트 캠프: React 과정` 면접을 수요일에 보게 되어 오늘까지만 알고리즘 공부를 하고 화요일에는 면접 준비에 집중하고 싶어 2문제만 풀이를 하게 됐습니다.
- topic: Array, Hash Table, Design, Matrix. Simulation
- review
- class 없이 객체를 어떻게 정의하라는 건지? 이해가 가지 않았다.
- ES5 문법으로는 어떻게 객체를 만들어내는 것인지 궁금하여 인터넷에 검색해보았다.
- 참고 링크: https://dev.to/martyhimmel/javascript-es5-objects-3cce
- 생각보다 ES6문법과 비슷했다.
- this를 일반 함수에서 사용하게 되면 전역 객체를 가리킨다는 개념에 사로잡혀서 생성자 함수에서의 this의 역할을 까먹고 있었다.
- 문제에서 말하는 object를 초기화 하라는 말은 this를 사용하여 생성자 함수가 받는 파라미터인 grid를 초기화하면 되는 것이었다.
- 생성자 함수로 쓰이는 함수 내부에서 this는 생성자 함수로 인해 만들어지는 객체를 가리킨다.
- `adjacentSum(value)` 메서드는 value 값을 grid 배열에서 어느 위치에 있는지 i와 j 인덱스 값을 찾아서 해당 위치에 인접한 상, 하, 좌, 우에 있는 요소들을 더한 값을 반환하는 함수를 …
> [Weekly contest 409] [Lucy] 13주차 2문제 풀이

- Gombang/Weekly Contest 409/3242_Design_Neighbor_Sum_Service.cs
- Gombang/Weekly Contest 409/3243_Shortest_Distance_After_Road_Addition_Queries_I.cs
Q. Design Neighbor Sum Service
---
- 해당 문제는 처음에 봤을 때 굉장히 당황스러웠던 문제였습니다. 일반적인 알고리즘 문제와는 다르게 클래스를 만드는 과정에 대한 문제였는데, 특별한 방법은 사용하지 않고 주어진 문제대로 인덱스 범위를 주의하면서 문제를 풀이하였습니다.
Q. Shortest Distance After Road Addition Queries I
---
- 해당 문제는 BFS를 이용하여 문제를 풀이하였습니다. 
- 0번 인덱스부터 n-1인덱스까지의 도시들을 단방향으로 이루어진 다리를 미리 준비해놓고, 인자로 들어오는 새로운 다리를 추가해가면서 bfs를 통해 거리를 계산하였습니다. 
- C#에서 튜플이라는 개념을 통해, 자료형을 `Queue<(int node, int distance)> queue = new Queue<(int node, int distance)>();` 이런 식으로 진행하여 node와 distance를 동시에 넣을 수 있도록 진행하였습니다.
> [Weekly contest 409] [Gombang] 13주차 2문제 풀이

- Seori/Weekly Contest 409/3242. Design Neighbor Sum Service.py
- Seori/Weekly Contest 409/3243. Shortest Distance After Road Addition Queries I.py
- Seori/Weekly Contest 409/3244. Shortest Distance After Road Addition Queries II.py
**3242. Design Neighbor Sum Service**
---
- 단순하게 2중 for문을 돌며 `(i, j)` 좌표를 찾고서 인접한 값을 더하는 코드를 작성했다.
- `class`를 조금 더 능숙하게 다룰 수 있으면 훨씬 최적화할 수 있었을 텐데 아쉽다. 자바공부 열심히 해야지
**3243. Shortest Distance After Road Addition Queries I**
---
- 처음에는 손에 익은 `DFS`로 접근하였으나, 문제 범위가 작음에도 `TLE`가 발생했다.
- 최단 거리를 찾는 문제이므로 `BFS`로 접근하여 해결할 수 있었다.
**3244. Shortest Distance After Road Addition Queries II**
---
- 2번째 문제 풀이를 발전시켜보려 했으나 쉽지 않았다.
- `세그먼트 트리`라는 자료구조를 공부하여 적용해보려 했지만 능숙하게 하지 못했다.
- 유튜브 강의에서 `Union-Find` 알고리즘에 착안하여 풀이한 것을 보고서 구현하여 해결했다.
- 도시의 연결관계인 `queries`가 교차하지 않는다는 조건이 있었으므로, 이미 연결된 도시는 하나의 `union`으로 만들어도 상관없다는 논리의 풀이방식이다.
> [Weekly Contest 409] [Seori] 13주차 3문제 풀이

- Gombang/Weekly Contest 410/3248_Snake_in_Matrix.cs
- Gombang/Weekly Contest 410/3249_Count_the_Number_of_Good_Nodes.cs
Q. Snake in Matrix
---
- 해당 문제는 2차원 배열로 진행하지 않고 1차원 배열로 진행하였습니다.
- Dictionary를 통해 UP, DOWN, LEFT, RIGHT에 대해 Key값으로 지정하였고, 각 Key값에 따라 얼마나 움직여야 하는지에 대해 Value로 지정하였습니다.
- 혹시나 commands에 인덱스 범위가 벗어나는 경우의 움직임이 들어오는지를 처리해야하나 싶었지만, 제한사항을 확인해보니 바운더리 외부로 움직이게 되는 경우는 인풋으로 들어오지 않는다는 내용이 있어서 특별히 처리하지 않았습니다.
Q. Count the Number of Good Nodes
---
- 개인적으로 문제를 읽어보고 예시를 확인해봐도 이해하기가 굉장히 어려웠던 문제였습니다.
- 각 노드마다 자식들의 서브노드의 개수가 서로 같은지를 체크하여, 같으면 현재 노드를 GoodNode로 처리하는 방식의 문제였는데, 경로를 만들어주는 것까지는 진행하였었으나 추가적으로 문제풀이에 어려움을 느껴 솔루션을 보고 진행하였습니다.
- 그래프의 경로를 설정해줄 때, 양방향으로 설정해주는 과정이 존재했는데 한 쪽 방향으로만 설정해주면 되지 않을까? 싶었지만, 한 쪽 방향으로만 설정해줄 경우 테스트 케이스에서 edge의 시작이 0이 아닌 노드로 시작이 될 경우 문제가 발생하여 양 방향으로 처리를 진행하였습니다. -> [testcase 145] edge : [[6,0],[1,0],[5,1],[2,5],[3,1],[4,3]] <br><br> 해당 테스트 케이스에서 문제가 발생한 이유는 그래프에 대해 서브트리의 개수를 계산하는 …
> [Weekly contest 410] [Gombang] 14주차 2문제 풀이

- Seori/Weekly Contest 410/3248. Snake in Matrix.py
- Seori/Weekly Contest 410/3249. Count the Number of Good Nodes.py
**3248. Snake in Matrix**
---
- 주어지는 방향값에 따라 (i, j) 좌표를 찾고서, 규칙에 맞게 해당 좌표의 값을 반환하였다.
- 문제 조건에서 범위 바깥으로는 이동하지 않는다고 해서 훨씬 간단하게 풀 수 있었다.
**3249. Count the Number of Good Nodes**
---
- 2번째 문제이나 풀이에 실패했다. 충격.. 더 붙들고 있을 수는 없어서 아쉽지만 포기했다.
- 오해 1. `good` 여부는 리프 노드까지가 아닌, 인접한 자식만 두고서 비교하는 줄 알았다.
- 오해 2. 0번 노드가 트리의 루트 노드일 때만 가정하여 함수를 작성했다.
> [Weekly Contest 410] [Seori] 14주차 1문제 풀이

- Lucy/Weekly Contest 411/3258_Count_Substrings_That_Satisfy_K-Constraint_I.js
- Lucy/Weekly Contest 411/3259_Maximum_Energy_Boost_From_Two_Drinks.js
- Lucy/Weekly Contest 411/3260_Find_the_Largest_Palindrome_Divisible_by_K.js
> 이번주도 문제가 많이 어렵네요... Easy만 혼자 힘으로 풀 수 있었습니다... 알고리즘 공부는 끝이 없는 것 같습니다.
- topic: String, Sliding Window
- review
- 처음 문제를 읽었을 때는 이게 무슨 문제지...? 싶었다. 노트에 s 문자열에서 나올 수 있는 substring을 모두 적어 놓고 K-Constraint 에 만족하는 것들을 세보았다. substring의 길이는 1부터 s의 길이만큼 자르면 됐고 각 substring에서 1의 갯수, 0의 갯수를 세서 K-Constraint에 만족하는 substring을 센 값을 반환하는 문제였다.
- 배열의 메서드를 사용하기 위해 String.prototype.split() 메서드를 사용하여 인자 s를 배열로 변환한 값을 splited에 저장했다.
- 2중 for 문을 사용하여 substring의 길이만큼 반복하고 내부에서는 substring을 구하여 1의 갯수와 0의 갯수를 세어 K-Constraint에 만족하면 cnt 변수의 값을 1 증가했다. 모든 반복이 끝나고 cnt 변수를 반환하여 문제를 풀이했다.
- K-Constraint에 해당되는지 판단하기 위해 substring 배열에 filter() 메서드를 사용할 때, 처음에는 동등 연산자(==)를 사용하여 filter 함수에서 요소를 필터링했다가 동등 연산자보다는 일치 연산자(===)가 좀 더 빠르다는 얘기를 들어서 일치 연산자를 사용해서 필터링 하도록 변경했다. 실제로 Leet Code에 처음에는 동등 연산자를 사용한 코드를 제출하고 …
> [Weekly contest 411] [Lucy] 15주차 2문제 풀이

- Seori/Weekly Contest 411/3258. Count Substrings That Satisfy K-Constraint I.py
- Seori/Weekly Contest 411/3259. Maximum Energy Boost From Two Drinks.py
- Seori/Weekly Contest 411/3260. Find the Largest Palindrome Divisible by K.py
> 지난 주에 2번을 못 풀기도 했고, 이번에 백준 플랫폼에서 진행하는 사내 코딩대회에 참가하기로 해서 3번까지 이악물고 열공했다.
**3258. Count Substrings That Satisfy K-Constraint I**
---
- 이게 Easy가 맞나 싶을 정도로 번거로웠어서 놀랐다. 내가 이해를 잘못한 줄 알았다.
- 가장 큰 `substring`부터 탐색 크기를 줄여가면 불필요한 탐색을 줄일 수 있다는 점에서 접근했다.
- 평소에 잘 못 써본 `슬라이딩 윈도우` 알고리즘을 활용할 수 있었다.
**3259. Maximum Energy Boost From Two Drinks**
---
- 점화식을 떠올리느라 고생했던 `DP`문제였다.
- 바꿔마시는 경우를 어떻게 식으로 나타낼 지 고민하느라 시간이 오래 걸렸다.
- 최대값을 비교할 때, `바꿔마신다` 보다 `바꿔 마시러 온다`는 관점으로 접근해야 생각하기 쉬웠다.
**3260. Find the Largest Palindrome Divisible by K**
---
- 쉬운 듯 어려운 듯 수학인 듯 수상한 Hard 문제였다.
- `k`가 `6, 7`인 경우에 막혀서 모범답안을 참고했다.
- 수학이 어려울 땐 컴퓨터에 의존하면 된다는 사실을 깨우쳐주는 신기한 문제였다.
> [Weekly Contest 411] [Seori] 15주차 3문제 풀이

- Gombang/Weekly Contest 412/3264_Final_Array_State_After_K_Multiplication_Operations_I.cs
- Gombang/Weekly Contest 412/3265_Count_Almost_Equal_Pairs_I.cs
- Gombang/Weekly Contest 412/3266_Final_Array_State_After_K_Multiplication_Operations_II.cs
Q. Final Array State After K Multiplication Operations I
---
- 해당 문제는 각 배열에 최소값에 해당하는 인덱스를 찾아서 해당 인덱스의 값에다가 multiplier값을 곱해서 업데이트 하는 방식으로 진행하였습니다.
- 제한조건도 특별히 신경써야 했던 부분은 없었어서 크게 어렵지 않게 풀 수 있었습니다.
Q. Count Almost Equal Pairs I
---
- 처음에 문제를 보고, 어떤 값이 주어졌을 때 두 요소를 스왑하여 나올 수 있는 모든 숫자를 반환하는 함수를 만들어서 이중 for문으로 쭉 풀면 되지 않을까? 싶은 생각이 들어서 그대로 진행했지만, example에 있는 '0'의 개념에 대해서는 해결하지 못하였습니다. 그래서 solution을 보고 풀이를 진행하였습니다.
- 솔루션의 풀이를 보니,
1. 소트를 진행한다.
<t> 배열의 순서가 필요한 문제는 아니므로 오름차순으로 정렬을 진행한다.
2. 이중 포문을 사용하여 0번째 인덱스부터 다른 인덱스들을 차례대로 비교해가며, str1의 길이가 str2길이보다 부족한 한큼 str1문자열에 '0'의 문자를 추가한다.
3. str1과 str2를 비교해가며 서로 다른 문자를 가진 인덱스를 따로 diffIndexList라는 list에 저장해둔다.
4. 정답 개수 증가.
<t> 4-1) diffIndexList의 개수가 0이면 두 문자열이 같은 것이므로 정답 카운트 증가.
<t> 4-2) diffIndexList에는 개수가 2개가 아니면 패스.
<t> 4-3) diffIndexList가 2개라면 그 두 개에 …
> [Weekly Contest 412] [Gombang] 16주차 2문제 풀이

- Meli/Weekly Contest 412/3264.Final_Array_State_After_K_Multiplication_Operations.py
- Meli/Weekly Contest 412/3265.Count_Almost_Equal_Pairs_I.py
- Meli/Weekly Contest 412/3266.Final_Array_State_After_K_Multiplication_Operations_II.py
1,2 번 문제는 무난했던 것 같고, 3,4번 문제는 시간 제한 안에 동작하지 않았습니다ㅠㅠ
> [Weekly Contest 412] [Meli] 16주차 2문제 풀이

- Lucy/Weekly Contest 412/3264_Final_Array_State_After_K_Multiplication_Operations_I.js
- Lucy/Weekly Contest 412/3265_Count_Almost_Equal_Pairs_I.js
> 이번 주도 프로젝트 캠프 참여하느라 3번째 문제는 풀 생각도 못했네요... 시간 분배를 다시 해보겠습니다. 이번 주도 수고하셨습니다!🫡
- topic: Array, Math, Heap, Simulation
- review
- for 문을 사용하여 k 번 연산을 반복하는 것을 표현한다.
- Math.min() 메서드와 spread operator를 사용하여 현재 nums 배열의 최솟값을 찾는다.
- Array.prototype.findIndex() 메서드를 사용하여 최솟값의 index를 찾는다.
- 최솟값 요소 * multiplier 계산한 값으로 업데이트한다.
- topic: Array, Hash Table, Sorting, Counting, Enumeration
- review
- Map 객체를 사용하여 nums 배열의 각 요소에 대해 각 자리 숫자의 빈도를 계산하였다. nums[i]와 nums[j]가 한 번의 swap 연산을 통해 동일한 숫자가 될 수 있는 경우를 찾아 카운트하려고 했다. 하지만...! 조건이 잘못됐는지 실패했다. 한시간 정도 고민하고 답이 나오지 않았기에 다른 사람의 풀이를 보고 공부하기로 결정했다.
- 배열을 순회하며 각 원소 nums[i]와 nums[j]를 문자열로 변환한다. 두 숫자의 자릿수를 맞추기 위해, 두 문자열의 최대 길이 maxLen을 구하고, 짧은 쪽에 앞에 "0"을 추가하여 길이를 동일하게 맞춘다. 변환된 두 문자열을 자릿수별로 비교하여 서로 다른 위치의 갯수를 센다. 각 문자열의 자릿수별로 …
> [Weekly contest 412] [Lucy] 16주차 2문제 풀이

- Meli/Weekly Contest 413/3274. Check if Two Chessboard Squares Have the Same Color.py
- Meli/Weekly Contest 413/3275. K-th Nearest Obstacle Queries.py
열별로, 행 별로 비교하는 로직으로 해결
원점으로부터 k개의 최소 거리를 최대 힙으로 업데이트하면서, k 번째 거리를 구함
> [Weekly Contest 413] [Meli] 17주차 2문제 풀이

- Lucy/Weekly Contest 413/3274_Check_if_Two_Chessboard_Squares_Have_the_Same_Color.js
- Lucy/Weekly Contest 413/3275_K-th_Nearest_Obstacle_Queries.js
> 3번째 문제를 풀이하던 중...프로젝트 관련해서 이슈가 생겨서 이번주 문제 풀이도 2문제만 풀이를 하게 됐습니다...🥹 프로젝트가 9월 말에 끝나는데 그 때까지는 2문제만 풀이를 할 수 있을 것 같습니다...!
- topic: Math, String
- review
- a, c, e, g의 홀수는 black, 짝수는 white라는 규칙과 b, d, f, h의 홀수는 white, 짝수는 black 이라는 규칙을 Map 객체로 표현하였다.
- coordinate1, coordinate2 를 String.prototype.split() 메서드를 사용하여 배열로 만든 후, getSquareColor() 함수의 인자로 넘겨서 각각의 색을 알아온다.
- 인자로 넘겼을 때, 배열 구조 분해 할당 문법을 사용해서 x에는 문자가 y에는 숫자가 담기는데, y로는 isEven() 함수로 홀짝을 판별한다. 그 후 결과에 따라 coordinateMap 객체에 Map.prototype.get() 메서드를 사용하여 좌표에 따른 체스 보드의 색을 반환한다.
- 마지막으로 coordinate1 과 coordinate2의 체스 보드 색을 비교하여 정답을 찾아낸다.
- topic: Array, Heap(Priority Queue)
- review
- Heap(Priority Queue)를 사용하여 문제를 풀 수 있었다.
- 첫 번째 풀이는 min heap을 사용하여 enqueue(), size(), toArray() 메서드를 사용하여 문제를 풀이했는데... 시간 …
> [Weekly Contest 413] [Lucy] 17주차 2문제 풀이

- Gombang/Weekly Contest 413/3274_Check_if_Two_Chessboard_Squares_Have_the_Same_Color.cs
- Gombang/Weekly Contest 413/3275_K-th_Nearest_Obstacle_Queries.cs
- Gombang/Weekly Contest 413/3276_Select_Cells_in_Grid_With_Maximum_Score.cs
Q. Check if Two Chessboard Squares Have the Same Color
---
- 처음에 해당 문제를 보고 어떻게 풀이를 할까 고민하다가, 체스판이 흑, 백이라는 것이 차례대로 규칙성이 존재하므로 알파벳과 숫자에 대해서 아스키값을 계산하여 풀이하면 될 것 같다는 생각으로 문제를 접근하였습니다.
- 알파벳의 아스키값과 숫자를 더했을 때 두 수의 합이 짝수이면 검은색 발판이고 홀수면 하얀색 발판이 된다는 것을 확인하여 해당 방식으로 풀이를 진행하였습니다.
Q. K-th Nearest Obstacle Queries
---
- 가장 간단한 방법인, for문을 돌려가며 정렬을 진행하여 k번째로 작은 값을 구하는 방식으로 진행했었는데 이는 시간초과가 발생하게 되어 힌트를 참고하게 되었습니다.
- 최대힙을 이용한다는 힌트를 참고하여 'k번째로 작은 수' 라는 개념을 어떻게 표현할 수 있을지 고민하다가 chatgpt에 물어보니 k개가 초과가 되면 Dequeue를 하여, 계속 k번째로 작은 수가 가장 상위에 존재할 수 있도록 유지하면 된다는 것을 알려주어 해당 방식으로 풀이를 진행하게 되었습니다.
> [Weekly Contest 413] [Gombang] 17주차 2문제 풀이

- Lucy/Weekly Contest 414/3280_Convert_Date_to_Binary.js
- Lucy/Weekly Contest 414/3281_Maximize_Score_of_Numbers_in_Ranges.js
- Lucy/Weekly Contest 414/3282_Reach_End_of_Array_With_Max_Score.js
> 추석 연휴가 껴있어서 문제를 풀 수 있는 시간은 많았으나... 연휴에 푹 쉬다보니 조금 늦게 올리게 됐네요!
- topic: Math, String
- review
-  String.prototype.split() 메서드를 사용하여 매개변수로 주어진 date의 값을 분리한다.
- 분리한 값을 Array.prototype.map() 메서드를 사용하여 Number 타입으로 형 변환을 한다.
- Number.prototype.toString() 메서드를 사용하여 toString()메서드에 인자로 2 값을 주어 이진수로 변환한다.
- 문제에서 요구하는 반환값 형태로 반환한다.
- Number.prototype.toString() 메서드를 사용하여 이진수로 변환할 수 있다는 걸 기억하고 있어서 쉽게 문제를 풀어낼 수 있었다.
- topic: Array, Binary Search, Greedy, Sorting
- review
- 이번 contest 문제 중에서 제일 어려웠던 문제라고 생각한다... 문제 이해하는 것부터 어려웠다.
- start: 정수 배열. 각 값이 구간의 시작점, d: 정수. 각 구간의 길이는 d로 고정됨
- 구간: [start[i], start[i] + d]
- 각 구간에서 하나의 숫자를 선택 > n개의 구간에서 선택한 숫자들 중, 가장 작은 두 숫자 간의 차이를 구함 > 구한 차이 중 최대화한 값이 score가 됨
- 해당 문제의 목표? 선택한 숫자들 사이의 최소 차이를 최대한 크게 만드는 것이 목표
- binary …
> [Weekly Contest 414] [Lucy] 18주차 3문제 풀이

- Seori/Weekly Contest 414/3280. Convert Date to Binary.py
- Seori/Weekly Contest 414/3282. Reach End of Array With Max Score.py
- Seori/Weekly Contest 415/3289. The Two Sneaky Numbers of Digitville.py
- Seori/Weekly Contest 415/3290. Maximum Multiplication Score.py
**3280. Convert Date to Binary**
---
- `format()` 메서드를 사용하면 2진수, 8진수, 16진수 등의 문자열 형태로 간단하게 변환할 수 있다.
**3281. Maximize Score of Numbers in Ranges**
---
- 문제를 이해하기도 힘들었고 푸는 방법도 복잡해보여서 영 손대지 못했다..😭
**3282. Reach End of Array With Max Score**
---
- `nums` 배열의 앞에서부터 가장 최대값만을 더하면 되는 문제라 간단하게 해결했다!
**3289. The Two Sneaky Numbers of Digitville**
---
- `index()` 메서드는 중복값이 있더라도 가장 앞의 인덱스만 반환하므로 그 원리를 이용했다.
- 풀이는 간단했지만 방식이 여러 가지 나올 것 같아 재미있는 문제였다.
**3290. Maximum Multiplication Score**
---
- 이번에도 보자마자 DP 유형이라고 생각하고 풀이를 시작했다.
- 숫자 4개를 선택하는 분기를 4개의 배열에 담아 풀이했다.
- 수의 범위가 커서 INF를 적당히 크게했더니 오답 케이스가 발생했었다. 문제 최대 범위에 유의하자.
> [Weekly Contest 414&415] [Seori] 18주차 2문제 및 19주차 2문제 풀이

- Lucy/Weekly Contest 414/3280_Convert_Date_to_Binary.js
- Lucy/Weekly Contest 414/3281_Maximize_Score_of_Numbers_in_Ranges.js
- Lucy/Weekly Contest 414/3282_Reach_End_of_Array_With_Max_Score.js
- Lucy/Weekly Contest 415/3289_The_Two_Sneaky_Numbers_of_Digitville.js
> 6주간의 프로젝트 캠프 발표회가 있어 알고리즘 스터디에 시간을 많이 쏟아붓지 못했습니다...🥲 다음주에는 열심히 참여하도록 하겠습니다!
- topic: Array, Hash Table, Math
- review
- 매개변수로 주어진 nums에서 중복되는 숫자를 찾아서 오름차순으로 정렬한 값을 반환하면 된다고 생각했다.
- 중복되는 수를 찾기 위해서 cntMap 이라는 Map 객체를 사용했다.
- Array.prototype.forEach() 메서드를 사용하여 nums 배열을 순회하면서 cntMap에 각 숫자를 카운팅했다.
- cntMap은 Map 객체이기 때문에 Array.from() 메서드를 사용하여 배열로 바꿔 배열이 사용할 수 있는 메서드를 사용하여 중복되는 숫자들을 찾아냈다.
- Array.prototype.filter() 메서드를 사용하여 카운트가 1보다 큰 숫자들을 찾아내고, Array.prototype.map() 메서드를 사용하여 중복된 숫자들로만 이루어진 배열로 만들었다. 그 후, Array.prototype.sort() 메서드를 사용하여 중복된 숫자들을 오름차순으로 정렬하여 답을 구할 수 있었다.
> [Weekly Contest 415] [Lucy] 19주차 1문제 풀이

- Gombang/[LeetCode75] - [Array_Sort]/1071_Greatest_Common_Divisor_of_Strings.cs
- Gombang/[LeetCode75] - [Array_Sort]/1431_Kids_With_the_Greatest_Number_of_Candies.cs
- Gombang/[LeetCode75] - [Array_Sort]/1768_Merge_Strings_Alternately.cs
Q. Merge Strings Alternately
---
- 두 문자열을 번갈아가면서 더해주면 되는 문제였기 때문에 하나의 인덱스를 가지고 번갈아가면서 추가해주는 방식으로 문제를 풀이하였습니다. 마지막에는 끝까지 도달하지 못한 문자열이 있다면 남은 문자열 만큼 추가해주도록 처리하였습니다.
Q. Greatest Common Divisor of Strings
---
- 두 문자열이 동시에 나눠지기 위해서는 겹치는 문자열을 구해야 하기 때문에 0번째 인덱스부터 차례대로 비교해가며 동일할때마다 누적된 문자열을 divisorList라는 곳에 넣어주었고, IsDivisible이라는 헬퍼함수를 사용하여 두 문자열이 잘 나누어지는지를 체크하는 방식으로 진행하였습니다.
Q. Kids With the Greatest Number of Candies
---
- 해당 문제는 배열 중 max값을 먼저 구해놓고, 배열을 돌려가며 extraCandies를 더했을 때 max값보다 크면 true를 작으면 false를 넣어주는 식으로 풀이하였습니다. 가장 간단했던 문제였지 않나 싶다.
> [LeetCode75] [Gombang] 20주차 3문제 풀이

- Seori/LeetCode 75/Array_String/151. Reverse Words in a String.py
- Seori/LeetCode 75/Array_String/1768. Merge Strings Alternately.py
- Seori/LeetCode 75/Array_String/345. Reverse Vowels of a String.py
> 다시 초심으로 화이팅!! 
**1768. Merge Strings Alternately**
---
- `word1`과 `word2`의 길이를 비교하고 처리하는 부분이 관건이었다.
- for문 하나로 간결하게 구성하기 위해서 if문 2개를 사용해서 `word1`부터 순서대로 merge하도록 했다.
**345. Reverse Vowels of a String**
---
- 손이 많이 가서 평범한 Easy 문제는 아니었다고 생각한다.
- 모음 개수가 적기 때문에 먼저 `vowels`라는 변수로 생성해두고 비교할 때 사용하였다.
- 문자열은 위치를 바꿀 수 없기 때문에 `list` 자료형을 활용해서, 모음의 인덱스를 서로 바꿔주었다.
**151. Reverse Words in a String**
---
- 오히려 345번 문제보다 간단하게 해결됐다.
- `" "` 기준으로 split하게 되면 예제에 주어지는 `""` 공백도 `list`에 담기게 된다.
- 따라서 `""` 공백을 제거해주고, `list`를 역순으로 합쳐서 해결하였다.
> [LeetCode75] [Seori] 20주차 3문제 풀이

- Gombang/[LeetCode75] - [Array_Sort]/151_Reverse_Words_in_a_String.cpp
- Gombang/[LeetCode75] - [Array_Sort]/345_Reverse_Vowels_of_a_String.cpp
- Gombang/[LeetCode75] - [Array_Sort]/605_Can_Place_Flowers.cpp
| 최근에 다시 C++언어를 공부하면서 알고리즘 문제도 C++ 방식을 이용하여 풀어보게 되었습니다. 
Q. Can Place Flowers
---
- prev와 next가 배열 범위를 벗어난 경우, currIndex위치에 꽃을 놓는 것에는 영향을 미치지 않는다는 것을 어떻게 처리할까 하다가 currIndex를 넣어주는 방식으로 처리하였습니다. 이 부분이 코드적으로는 매끄럽지 못한 부분이여서 어떻게 처리하면 좋을지를 생각해보니, `bool prevIsEmpty = (currIndex == 0 || flowerbed[currIndex - 1] == EMPTY);` 이런 방식으로 prevIsEmpty라는 변수를 만드는 것은 어땠을까? 하는 생각이 뒤늦게 되었습니다.
Q. Reverse Vowels of a String
---
- 처음에는 vector를 이용해서 풀이를 진행해보려고 했으나, 계속해서 O(n)방식의 find방식으로 인해 더 좋은 방식을 찾아보다가 unordered_set이라는 자료구조를 처음 알게 되었습니다. 
- 보통 빠른 검색을 위해서는 키-값 구조인, unordered_map(해시 테이블 기반)이나 map(이진 탐색 기반)을 이용했었는데 unordered_set 자료구조를 알게 되었습니다. 키-값 구조가 아니라 단순하게 유니크한 데이터의 모음을 만들 수 있는 자료구조이고, 해시테이블 기반이기 때문에 빠른 검색에 유리한 자료구조여서 unordered_set을 사용하게 되었습니다.
Q. Reverse Words in a String
---
- 특별한 방식이 아닌, 무식한 방법으로 문자 하나하나 …
> [LeetCode75] [Gombang] 21주차 3문제 풀이

- Seori/LeetCode 75/Array_String/1071. Greatest Common Divisor of Strings.py
- Seori/LeetCode 75/Array_String/1431. Kids With the Greatest Number of Candies.py
> 이번 주는 여유가 없어서 2문제밖에 풀이하지 못했습니다😭 마음의 평온을 되찾았으면 좋겠네요☺️
**1071. Greatest Common Divisor of Strings**
---
- 고민하다가 Easy 문제이므로 간단하게 반복문으로 풀기로 했다. 문제 조건이 Medium이었다면 훨씬 골치아팠을 것 같다.
- 다른 사람들 풀이를 찾아보다가 Math 모듈의 gcd라는 함수로 쉽게 최대공약수를 구할 수 있다는 걸 배웠다!
**1431. Kids With the Greatest Number of Candies**
---
- 수학적으로 접근하여 풀이했다.
- 문제 조건을 요약해보면 결국 `각 인덱스의 캔디 수`가 `캔디의 최대값에서 extraCandies를 뺀 값`보다 큰지 작은지 비교하는 문제여서 이를 `net_candies`로 정의해서 풀었다.
> [LeetCode75] [Seori] 21주차 2문제 풀이

- Lucy/LeetCode 75/Array_String/238_Product_of_Array_Except_Self.ts
- Lucy/LeetCode 75/Array_String/334_Increasing_Triplet_Subsequence.ts
- Lucy/LeetCode 75/Array_String/443_String_Compression.ts
- Lucy/tsconfig.json
- 문제에서 시간복잡도가 O(n)인 풀이를 하라고 했지만 생각나는 방법은 O(n^2) 풀이 방법이어서 우선 풀어봤다. for문과 Array.prototype.filter() 메서드를 사용해서 i 인덱스와 일치하지 않는 값들을 filter()메서드로 추려낸 후 Array.prototype.reduce() 메서드로 i 인덱스의 요소를 제외한 값들의 곱을 구해냈다. Time Limit Exceeded 에러가 떠서 다른 풀이를 생각해내야 했다.
- Hint를 봐도 이해가 되지 않았기에 Discuss 탭에서 다른 사람의 풀이를 보고 prefix(i 이전 요소들의 곱한 값), suffix(i 이후 요소들의 곱한 값)을 구한 후, prefix[i] * suffix[i]로 값을 구할 수 있었다.
- 첫 번째 접근 방법은 isIncreases라는 배열을 nums.length - 1 길이로 생성하고, 각 요소에 nums[i] < nums[i + 1] 조건을 기록했습니다. 이 배열은 각 요소가 다음 요소보다 작은지를 판단해 증가하는 구간인지 표시해줍니다. isIncreases 배열에서 true의 개수가 2개 이상인 경우 true를 반환하여 삼중항이 존재함을 나타내도록 했습니다. 문제점: 이 접근 방식은 nums[i] < nums[j] < nums[k]를 만족하는 정확한 삼중항 조건을 확인하지 못하고, 단순히 인접 요소들 간의 증가만을 파악했습니다.
- 그래서 Discuss 탭에서 다른 사람의 풀이를 참고했습니다. 여기서는 두 개의 변수 a와 b를 초기 최대값(MAX)으로 설정한 후, for ... of 문을 사용해 nums …
> [LeetCode75] [Lucy] 22주차 3문제 풀이

- Gombang/[LeetCode75] - [Array_Sort]/238_Product_of_Array_Except_Self.cpp
- Gombang/[LeetCode75] - [Array_Sort]/334_Increasing_Triplet_Subsequence.cpp
- Gombang/[LeetCode75] - [Array_Sort]/443_String_Compression.cpp
Q. Product of Array Except Self
---
- 처음에는 나누기 연산풀이법과 이중 포문을 이용한 풀이 방법밖에 생각이 나지 않아 어떻게 풀어야 될지 감이 잡히지 않아서 다른사람의 풀이를 참고하게 되었습니다.
- 본인을 기준으로 좌측에 대한 값들의 곱들을 넣어준 후, 우측에 대한 값들의 곱을 넣어주면 본인을 제외한 나머지 값들의 곱을 구할 수 있음을 이용하였습니다.
Q. Increasing Triplet Subsequence
---
- 처음에는 인접한 세 개의 값이 오름차순으로 정렬되어 있는지를 체크하는 방식인줄 알고 해당 방식으로 구현했다가, 세 개의 값을 기준으로 오름차순이 존재하는지를 구하는 문제라는 것을 알게 되었습니다. 뭔가 코드가 계속 꼬이고 꼬여.. 솔루션을 참고하여 풀이를 하게 되었습니다.
-  firstMinValue라는 값과 secondMinValue라는 값을 이용하여 오름차순이 존재하는지를 파악하는 방법으로 문제를 풀게 되었습니다.
Q. String Compression
---
- count와 currChar라는 변수를 이용하여, currChar와 동일한 문자이면 count를 증가시켜주고, 동일한 문자가 아니라면 vector에 문자와 count변수를 넣어주는 방식으로 진행하였습니다.
> [LeetCode75] [Gombang] 22주차 3문제 풀이

- Lucy/LeetCode 75/Two_Pointers/11_Container_With_Most_Water.ts
- Lucy/LeetCode 75/Two_Pointers/283_Move_Zeroes.ts
- Lucy/LeetCode 75/Two_Pointers/392_Is_Subsequence.ts
- 처음에 Array.prototype.splice() 메서드를 사용해서 nums에서 0인 요소를 제거하고 뒤에 0을 추가하는 식으로 구현했는데 [0, 0, 1] 인 테스트 케이스에서 실패를 했다.
- 그래서 다른 방법을 생각한 끝에 nonZeroes 라는 변수에 nums에서 0이 아닌 값들을 요소로 가지는 배열을 생성하고 for문을 사용해서 nonZeroes의 길이만큼 nums에 있는 값들을 nonZeores 값으로 재할당하고 나머지 인덱스는 0으로 채워넣는 방식으로 문제를 해결했다.
- 다른 사람들의 풀이를 보니까 two pointers 개념으로 풀이를 했던데 다음에 풀어볼 때는 two pointers 개념을 사용한 풀이로 다시 풀어봐야겠다.
-  s의 인덱스를 가리키는 sPointer, t의 인덱스를 가리키는 tPointer를 사용하여 s가 t의 subsequence인지 판별했다. while문으로 tPointer가 t 문자열을 모두 순회할 때까지 반복하여 sPointer에 위치한 문자와 tPointer에 위치한 문자가 같을 때만 sPointer 값을 증가시켰다. 마지막으로 sPointer가 s 문자열의 길이와 일치하는지를 비교한 값을 반환하여 문제를 풀이하였다.
- 처음에 left, right 포인터를 사용해서 (left, right), (left + 1, right), (left, right - 1), (left + 1, right - 1) 4경우를 한 번에 비교해서 area를 업데이트 하고 left, right 포인터를 아무 조건없이 업데이트를 했더니 답을 틀렸다.
- 그래서 다른 사람의 풀이를 …
> [LeetCode75] [Lucy] 23주차 3문제 풀이

- Seori/LeetCode 75/Two Pointers/11. Container With Most Water.py
- Seori/LeetCode 75/Two Pointers/283. Move Zeroes.py
- Seori/LeetCode 75/Two Pointers/392. Is Subsequence.py
**283. Move Zeroes**
---
- 처음에는 양쪽 끝에서 포인터로 위치를 바꾸는 문제인 줄 알고 잘못 풀었다.
- 0 이외의 원소 순서를 유지하기 위해서 `pop`과 `append` 메서드를 사용했다.
- `append`되는 0을 다시금 처리하지 않기 위해 `right` 포인터를 -1처리 해주었다.
**392. Is Subsequence**
---
- 문자열을 하나씩 읽으면서 `left` 포인터가 `right`에 도달했다면 `True`를 반환하도록 했다.
- 입력값 `s`의 범위가 0일 수 있었기 때문에 오답 이후 케이스를 추가하였다.
- 챌린지 조건은 잘 감이 안와서 그냥 넘겼다.
**11. Container With Most Water**
---
- O(n) 풀이를 떠올리기 힘들어 디스커션을 참고했다. 역시 Medium... 만만치 않다.
- 문제에서 직사각형의 넓이를 좌우하는 것은 양쪽 중 높이가 낮은 쪽이다.
- 따라서 높이가 낮은 쪽을 움직여가며 넓이를 측정해가면 최적값을 구할 수 있었다.
> [LeetCode75] [Seori] 23주차 3문제 풀이

- Lucy/LeetCode 75/Sliding Window/1456_Maximum_Number_of_Vowels_in_a_Substring_of_Given_Length.ts
- Lucy/LeetCode 75/Sliding Window/643_Maximum_Average_Subarray_I.ts
- Lucy/LeetCode 75/Two Pointers/1679_Max_Number_of_K-Sum_Pairs.ts
- 처음에는 문제의 Hint를 보고 count(x), count(k - x)의 값을 구해서 풀이를 했는데 조건도 복잡하고 모든 테스트 케이스를 통과하지 못했다.
- Two Pointers 유형인 것을 생각해서 풀어보려 했으나 풀이가 떠오르지 않아 다른 사람의 풀이를 참고해서 풀이하게 됐다. nums 배열을 Array.prototype.sort() 메서드를 사용해서 오름차순으로 정렬을 한다. left는 nums 배열의 첫 번째 인덱스를 right는 nums 배열의 마지막 인덱스를 가리킨다. while문은 left, right 포인터가 겹칠 때까지 반복한다. sum 변수에 left, right 포인터가 각각 가리키는 nums 배열의 요소를 더한 값을 저장하고 k와 같을 때, k보다 클 때, k보다 작을 때, 3경우를 나누어 포인터의 값을 증가, 감소 시키고 countOperations 변수의 값을 증가시켜 답을 풀이할 수 있었다.
- Two Pointers 라는 유형의 경우 두 개의 포인터를 어떻게 이용할 것인지 고민하는 습관을 들여야겠다.
- 슬라이딩 윈도우 알고리즘에 대해 공부한 후, 해당 문제를 풀어낼 수 있었다.
- sum과 maxAverage에 초기값을 구하여 정의한 후, nums 배열을 index 1부터 nums 배열 길이 - k까지 for문을 사용하여 순회한다. for문에서는 sum의 값을 nums[i-1] 값을 빼고 nums[i + k - 1] 값을 빼서 업데이트 한다. currentAverage에는 업데이트 된 sum 값을 기준으로 평균값을 구하여 저장한다. maxAverage는 …
> [LeetCode75] [Lucy] 24주차 3문제 풀이

- Gombang/[LeetCode75] - [Prefix Sum]/1732_Find_the_Highest_Altitude.cpp
- Gombang/[LeetCode75] - [Sliding Window]/1004_Max_Consecutive_Ones_III.cpp
- Gombang/[LeetCode75] - [Sliding Window]/1493_Longest_Subarray_of_1's_After_Deleting_One_Element.cpp
1004 Max Consecutive Ones III
---
- 여러 시행착오가 있었지만 잘 해결되지 않아 다른 사람의 풀이를 보고 진행하게 되었습니다.
- 0이라는 값을 만나게 되면 zeroCount라는 변수를 증가시켜주게 되고, zeroCount의 값이 k보다 커지면 left에 해당하는 인덱스를 땡겨오는 방식으로 진행하였습니다. 
1493 Longest Subarray of 1's After Deleting One Element
---
- 이 문제를 자세히 보니 전 문제였던 1004번에 해당하는 풀이법과 동일하게 풀어도 해결되는 것을 확인할 수 있었습니다(max값을 구할 때 1004번 문제는 `right - left + 1`을 해줘야 되지만, 이 문제는 `right - left` 만 해주는 것을 제외하고는 모든 풀이가 동일).
- 1004번의 문제는 k라는 개념때문에 카운팅의 개념이 들어가서 zeroCount라는 것을 활용하였지만, 이 문제는 카운팅의 개념은 딱히 필요가 없어서 isDeleted라는 변수를 통해 풀이되도록 풀이를 변경해보았습니다.
- 0의 다음 값을 가리키기 위해 0이 나오지 않을 때까지 left의 값을 증가시켜주고 마지막에 +1을 해줘서 다음 값을 가리키도록 설정하였습니다.
```
// 이미 0을 삭제한 경우에는 슬라이딩 윈도우 크기 축소
while (nums[left] != 0)
left++;
left++; //최종적으로 0의 다음 인덱스를 가리키고 있음.
```
1732 Find the Highest Altitude
---
- 처음에 문제도 잘 이해가 안가고 예시에도 이상한 값들이 …
> [LeetCode75] [Gombang] 26주차 3문제 풀이

- Seori/LeetCode 75/Prefix Sum/1732. Find the Highest Altitude.py
- Seori/LeetCode 75/Sliding Window/1004. Max Consecutive Ones III.py
- Seori/LeetCode 75/Sliding Window/1493. Longest Subarray of 1's After Deleting One Element.py
>3주 동안 잦은 야근으로 피폐해진 삶을 극복하고 돌아왔습니다😭 여러분은 어떻게 지내셨나요~?
**1493. Longest Subarray of 1's After Deleting One Element**
---
- 아래 문제보다 이 문제를 먼저 풀었는데, Sliding Window 개념은 알고 있었으나 풀이 방식이 익숙하지 않았다.
- 그래서 나름대로 window를 의식하면서 `left`, `right`를 설정하고 규칙을 정해서 풀어보았다.
- 정답을 제출하고 나서 모범답안을 보며 Sliding Window 풀이법을 익히게 되었다.
**1004. Max Consecutive Ones III**
---
- 위 문제의 모범답안을 통해 익힌 풀이법을 적용했다.
- 문제마다 `k`와 return할 값이 달라질 뿐, 정형화된 풀이 방식이 있어서 더 익숙해져야겠다.
**1732. Find the Highest Altitude**
---
- Prefix Sum 유형의 Easy 문제였다.
- 일반적인 for문 탐색으로도 풀 수 있지만 유형을 의식하면서 풀어보았다.
> [LeetCode75] [Seori] 26주차 3문제 풀이

- Lucy/2025/W01/2215_Find_the_Difference_of_Two_Arrays.md
- Lucy/2025/W01/2215_Find_the_Difference_of_Two_Arrays.ts
- Lucy/2025/W01/724_Find_Pivot_Index.md
- Lucy/2025/W01/724_Find_Pivot_Index.ts
- Lucy/2025/W01/도넛과_막대_그래프.Md
- Lucy/2025/W01/도넛과_막대_그래프.js
25년 1주차 3문제 풀이했습니다.
프로그래머스 Lv2 문제인데도 많이 어렵네요.... 그래프 공부 다시해야겠습니다!
> [프로그래머스+LeetCode 75] [Lucy] 25년 1주차 3문제 풀이

- Seori/LeetCode 75/Hash Map_Set/2215. Find the Difference of Two Arrays.py
- Seori/LeetCode 75/Prefix Sum/724. Find Pivot Index.py
- Seori/Programmers/도넛과 막대 그래프.py
- Seori/TIL/25년 1주차 TIL.md
>방학과 리뉴얼을 맞이해서 마크다운으로 TIL 작성해봤습니다 :)
Prefix Sum 유형의 문제였기 때문에 먼저 누적합 리스트 `left_sum`을 만들면서 문제에 접근했다.
```python
def pivotIndex(self, nums: List[int]) -> int:
length = len(nums)
left_sum, right_sum = [0] * length, [0] * length
left_sum[0] = nums[0]
for i in range(0, length-1):
left_sum[i+1] = left_sum[i] + nums[i+1]
right_sum[length-1] = nums[length-1]
for i in range(length-1, 0, -1):
right_sum[i-1] = right_sum[i] + nums[i-1]
for i in range(0, length):
if left_sum[i] == right_sum[i]:
return i
return -1
```
문제 해결 조건은 해당 인덱스를 기준으로 좌측과 우측의 합이 전부 같은, 가장 빠른 인덱스를 찾는 것이었다. 따라서 첫 번째 풀이에서는 좌측부터 누적합 `left_sum`과 우측부터 누적합 `right_sum` 을 만들고, 다시 처음부터 탐색하며 해결 조건에 맞는 인덱스를 찾아냈다.
하지만 제출하고 나니 for 반복문을 3번 돌면서 비효율적이라는 생각이 들어서 코드를 개선했다.
```python
def pivotIndex(self, nums: …
```
> [프로그래머스+LeetCode 75] [Seori] 25년 1주차 3문제 풀이

- Meli/LeetCode 75/2215_Find_the_Difference_of_Two_Arrays.py
- Meli/LeetCode 75/724_Find_Pivot_Index.py
- Meli/Programmers/2024_kakao_winter_internship_donut_graph.py
- 누적합을 구하는 방식으로 문제 해결. answer 변수가 정답으로 원하는 index 값이며, left_sum, right_sum 변수가 각각 인덱스의 왼쪽과 오른쪽 합을 담는다.
```
def pivotIndex(self, nums: List[int]) -> int:
answer = 0
left_sum = 0
right_sum = sum(nums) - nums[0]
if left_sum == right_sum:
return answer
while left_sum != right_sum:
answer += 1
if answer >= len(nums):
answer = -1
break
left_sum += nums[answer-1]
right_sum -= nums[answer]
return answer
```
- set 자료형의 차집합 구하기
```
def findDifference(self, nums1: List[int], nums2: List[int]) -> List[List[int]]:
answer = [[],[]]
nums1, nums2 = set(nums1), set(nums2)
answer[0].extend(list(nums1-nums2))
answer[1].extend(list(nums2-nums1))
return answer
```
- 문제 파악이 어려웠고, 생성되는 점은 보내는 간선만 있다는 특징으로 찾기 용이했지만, 그래프의 개수를 세는 것이 어려운 부분이었음.
- 각 그래프의 특징을 찾고 임의로 생성된 점에서 연결된 각 그래프의 …
> [프로그래머스+LeetCode 75] [Meli] 25년 1주차 3문제 풀이

- Meli/LeetCode 75/1207_Unique_Number_of_Occurrences.py
- Meli/LeetCode 75/1657_Determine_if_Two_Strings_Are_Close.py
- Meli/Programmers/2024_kakao_winter_internship_dice.py
leetcode 문제들은 구현을 금방 했지만, 카카오 코테 문제는 역시나 어려웠다. 여러 알고리즘들을 적재적소에 써야 하는데, 이 부분을 더 공부해야겠다. 카카오 문제 풀이는 50점을 받은 반쪽짜리 풀이이다(무식하게 다 for문을 돌았다). 시간초과를 해결하지 못했고, 이 부분에서 시간을 효율적으로 할 수 있는 알고리즘을 구현해봐야겠다.
> [프로그래머스+LeetCode 75] [Meli] 25년 2주차 2문제 풀이

- Seori/LeetCode 75/Hash Map_Set/2352. Equal Row and Column Pairs.py
- Seori/LeetCode 75/Stack/2390. Removing Stars From a String.py
- Seori/Programmers/n+1 카드게임.py
- Seori/TIL/25년 3주차 TIL.md
문제를 읽고 행렬의 순서를 돌려서 풀어야겠다고 생각했다.
문제 조건 범위에서 `n`이 최대 200이었기 때문에 2중 for문으로도 간단하게 해결할 수 있었다.
```python
def equalPairs(self, grid: List[List[int]]) -> int:
n = len(grid)
grid_counterclockwise = []
for i in range(n):
column = []
for j in range(n):
column.append(grid[j][i])
grid_counterclockwise.append(column)
answer = 0
for row in grid:
for column in grid_counterclockwise:
if row == column:
answer += 1
return answer
```
더 속도가 빠른 답안들은 주로 `Counter`를 사용해서 for문 반복 횟수를 줄여준 것들이었다. 확실히 `Counter`를 사용하는 풀이 방법이 `Hash Map/Set`이라는 알고리즘 유형에도 맞다는 생각이 든다. 전에 공부했었는데 아직 사용법이 익숙치 않아 더 습관화해야겠다.
이번엔 `Stack` 유형의 문제이다. 문제 유형을 알고 푸니 훨씬 간단한 문제였다.
유형을 안 읽고 풀다 보니 조금 헤맸었다.
```python
def removeStars(self, s: str) -> str:
n = s.count('*')
list_s = list(s)
for _ in range(n):
star = …
```
> [프로그래머스+LeetCode 75] [Seori] 25년 3주차 3문제 풀이

- Gombang/Programmers/n+1카드게임.cpp
- Gombang/[LeetCode75] - [Hash_Map_Set]/2352_Equal_Row_and_Column_Pairs.cpp
- Gombang/[LeetCode75] - [Stack]/2390_Removing_Stars_From_a_String.cpp
- 해당 문제는 행, 열에 대해서 동일한 쌍의 개수가 몇 개 존재하는지를 찾아내는 문제였다.
- 행에 대해서 문자열로 정리하여 해당 문자열을 key값으로 하는 해쉬맵을 만들었고, 열에 대해서도 문자열을 만들어내서 행에 대한 맵에 일치하는 쌍 만큼 카운팅하는 방식으로 처리하였습니다.
- 스택 문제인 것이 바로 느껴져서 스택 방식으로 바로 풀이하게 되었다. 특별히 어려웠던 점은 없었다.
- 해당 문제는 어떻게 풀어야 되나에 대해서 고민을 많이 했던 문제였다. 문제를 이해하는데에는 어려움이 없었지만 예시에 나온 내용을 어떻게 알고리즘으로 적용해야 하나를 계속 생각해보았지만 특별한 풀이법이 떠오르지 않았다.
- 새로운 카드를 2장 뽑았을 때 타겟 값이 되는 경우가 있지만 최대 라운드를 진행하기 위해서 오히려 그 카드를 버려야 하는 상황이 오는데 이러한 부분에서 무엇을 기준으로 판단해야 하는지에 대해서 정리하기가 어려웠고, 결국 문제는 풀이할 수 없었다.
- 결국 모임에서 풀이하신 분들의 풀이를 듣고 힌트를 얻게 되었는데, 핵심은 버린다는 카드를 저장해두고 활용하는 부분에 있었다. 버린다고 해서 지나가는 것이 아니라 해당 카드까지 확인하면서 코인을 없애는 방식으로 하면 크게 어렵지 않게 문제를 풀이할 수 있었다. 
- 이 문제를 통해 느낀점은 어떤 값을 활용할지 안할지에 대한 문제가 나올때는 활용하지 않는다고 할지라도 저장해둔다는 개념을 사용할 수 있겠다는 것을 느끼게 되었다.
> [프로그래머스+LeetCode 75] [Gombang] 25년 3주차 3문제 풀이

- Meli/LeetCode 75/394_Decode_String.py
- Meli/LeetCode 75/735_Asteroid_Collision.py
- Meli/Programmers/2024_kakao_winter_internship_tiling.py
- Meli/TIL/2025_w04.md
- TIL 디렉토리에 자세하게 작성.
- leet code 문제는 stack 을 활용하는 문제였고, 조건에 맞는 로직을 구현하는 부분이 주요했음. 시간, 공간 복잡도를 고려한 효율적 풀이를 더 고민해봐야겠다고 생각함.
- 프로그래머스 문제는 dp 문제 유형, 점화식을 생각해서 구현해서 풀이.
> [프로그래머스+LeetCode 75] [Meli] 25년 4주차 3문제 풀이

- Seori/LeetCode 75/Stack/394. Decode String.py
- Seori/LeetCode 75/Stack/735. Asteroid Collision.py
- Seori/Programmers/산 모양 타일링.py
- Seori/TIL/25년 4주차 TIL.md
예제를 보면서 이건 왜 부딪히고 이건 왜 안부딪히는지… 이해하기 힘든 문제였다.
요악하면 `asteriods`라는 리스트 안에서 각 숫자들이 자기 인덱스에서 숫자만큼 이동한다고 생각하면 됐다. 그러면 리스트 앞에 있는 음수들은 충돌 대상이 없기 때문에 계산의 편의를 위해서 미리 빼놓고, 충돌 처리를 해줬다.
```python
def asteroidCollision(self, asteroids: List[int]) -> List[int]:
'''
이해하기 힘든 문제였지만..
요약하면 asteroids 리스트 안에서 
우측으로 진행하는 양수와 좌측으로 진행하는 음수끼리 충돌이 일어난다.
따라서 양수가 나오는 부분부터 충돌 처리를 해주었다.
'''
n = 0
length = len(asteroids)
while n < length and asteroids[n] < 0:
n += 1
answer = asteroids[:n+1]
asteroids = asteroids[n+1:]
for asteroid in asteroids:
if asteroid > 0:
answer.append(asteroid)
else:
negative = asteroid
while answer and answer[-1] > 0:
positive = answer[-1]
if positive > -negative:
negative = 0
break
elif positive == -negative:
answer.pop()
negative = 0
break
elif positive < -negative: …
```
> [프로그래머스+LeetCode 75] [Seori] 25년 4주차 3문제 풀이

- Gombang/Programmers/산 모양 타일링.cpp
- Gombang/[LeetCode75] - [Stack]/394_Decode_String.cpp
- Gombang/[LeetCode75] - [Stack]/735_Asteroid_Collision.cpp
- 처음에는 이 문제를 보고 주어진 대로 예외처리 해가면서 문제를 풀면 크게 막힘 없이 풀 수 있을거라고 생각했지만, 3번정도 문제 풀이에 실패를 하고 꼬였던 코드를 다시 풀어보면서 문제를 해결할 수 있었습니다.  
- 풀이에 실패했던 부분은, 스택이 비어있을 때 새롭게 추가하는 부분과 동일한 소행성이 충돌했을 때 스택에 추가하지 않는 처리에서 코드가 꼬여있음을 확인하였고 정리하여 문제를 풀이할 수 있었습니다.
- 문제를 보고 맨 처음 느꼈던 부분은, 학부생때 자료구조를 공부할 때 수식에 관해서 괄호를 처리할 때에 대한 문제와 비슷하다는 느낌을 받았었습니다(하지만 다시 자세히보니 좀 다른 문제였습니다).
- 이전에 누적되었던 스트링 데이터를 열리는 괄호를 만나면 넣어주고, 닫히는 괄호를 만나면 pop을 해서 반복되는 횟수만큼 스트링 데이터를 누적해주는 방식으로 풀이를 하였는데 알고리즘 자체는 조금 헤매면서 풀이를 하게 되었습니다.
- 개인적으로 스택 문제 중에서 쉽지 않았던 문제였던 것 같습니다.
- 이 문제는 DP문제였는데 점화식을 세우는 데에 아예 손도 못댄 문제였습니다. 삼각형과 평행사변형, 마름모라는 개념이 나오는데 이런 도형에 대해서 어떤 식으로 접근을 해야 하는지 아예 일절 감이 오지 않았던 문제였습니다.
- 알고리즘 모임 시간에 Meli님의 풀이를 듣고 어떤 방식으로 문제에 접근해야 하는지에 대해서 알게되었습니다. 도형들은 문제에서 경우의 수를 구하기 위한 하나의 예에 불과했고 결국 그 도형들을 어떻게 배치 시킬 것인지에 대해서 작은 범위에서 하나하나 생각해주면 되는 문제였습니다.
- …
> [프로그래머스+LeetCode 75] [Gombang] 25년 4주차 3문제 풀이.

- Seori/LeetCode 75/Queue/649. Dota2 Senate.py
- Seori/LeetCode 75/Queue/933. Number of Recent Calls.py
- Seori/Programmers/택배 배달과 수거하기.py
- Seori/TIL/25년 6주차 TIL.md
오랜만에 만난 클래스 구현 문제다. 요구사항 자체는 간단해서 금방 구현할 수 있었고, LeetCode 환경 특성상 python 코드에 붙어 있는 `self` 처리 때문에 조금 애를 먹었다. 다른 IDE에서는 `self`가 생략되어 사용되지만, LeetCode 환경에서는 메서드를 정의할 때 가장 첫 인자로 `self`가 명시되어 있기 때문에 코드 작성 시 유의해야 한다.
```python
class RecentCounter:
def __init__(self):
self.queue = []
return None
def ping(self, t: int) -> int:
queue = self.queue
queue.append(t)
while queue[0] < t - 3000:
queue.pop(0)
return len(queue)
```
R과 D 정당이 투표를 통해 서로 싸운다는 이야기이다. 투표 순서에 따라 상대 정당을 퇴출하고 다시 투표 줄을 설 수 있으니 `queue` 유형에 적합한 문제였다.
```python
def predictPartyVictory(self, senate: str) -> str:
list_senate = list(senate)
while list_senate:
senator = list_senate.pop(0)
if senator == 'D':
if 'R' in list_senate:
list_senate.remove('R')
list_senate.append('D')
else: return 'Dire'
elif senator == 'R':
if 'D' in …
```
> [프로그래머스+LeetCode 75] [Seori] 25년 6주차 3문제 풀이

- Lucy/2025/2-W01/649_Dota2_Senate.md
- Lucy/2025/2-W01/649_Dota2_Senate.ts
- Lucy/2025/2-W01/933_Number_of_Recent_Calls.md
- Lucy/2025/2-W01/933_Number_of_Recent_Calls.ts
- Lucy/2025/2-W01/택배_배달과_수거하기.js
- Lucy/2025/2-W01/택배_배달과_수거하기.md
- Lucy/2025/2-W01/택배_배달과_수거하기_2.js
- Lucy/package-lock.json
- Lucy/package.json
- Lucy/tsconfig.json
Revert에 대해 잘못 생각해서 다시 취소하였습니다.
'택배 배달과 수거하기' 다시 풀이한 것 누락돼서 해당 풀이도 다시 올렸습니다.
> Revert 취소([프로그래머스+LeetCode 75] [Lucy] 25년 6주차 3문제 풀이)

- Lucy/2025/2-W02/2095_Delete_the_Middle_Node_of_a_Linked_List.md
- Lucy/2025/2-W02/2095_Delete_the_Middle_Node_of_a_Linked_List.ts
- Lucy/2025/2-W02/328_Odd_Even_Linked_List.md
- Lucy/2025/2-W02/328_Odd_Even_Linked_List.ts
- Lucy/2025/2-W02/이모티콘_할인_행사.js
- Lucy/2025/2-W02/이모티콘_할인_행사.md
- 연결 리스트 포인터는 아직 헷갈리지만 문제가 생각보다 재밌었다.
- 반복문으로 순회할 자료구조들이 많을 수록 머릿속에서 헷갈려서 정리가 잘 안된다. 헷갈릴 때는 손으로 써보면서 정리를 하는게 좋을 것 같다.
> [프로그래머스+LeetCode 75] [Lucy] 25년 7주차 3문제 풀이

- Seori/LeetCode 75/Linked List/2095. Delete the Middle Node of a Linked List.py
- Seori/LeetCode 75/Linked List/328. Odd Even Linked List.py
- Seori/Programmers/이모티콘 할인행사.py
- Seori/TIL/25년 7주차 TIL.md
7주차 문제 유형은 `Linked List`였다. 개념은 알고 있었지만 평소에 잘 사용할 일이 없어서 반가웠다. 문제 난이도 자체는 `Medium`이었으나 자료구조 자체가 단순해서 문제 풀이도 금방 떠올릴 수 있었다.
```python
def deleteMiddle(self, head: Optional[ListNode]) -> Optional[ListNode]:
def find_last_node(head: Optional[ListNode]) -> int:
cnt = 1
while head.next:
head = head.next
cnt += 1
return cnt
def deleteNode(head: Optional[ListNode], n: int) -> None:
for i in range(n-1):
head = head.next
head.next = head.next.next
n = find_last_node(head)
if n == 1: return
deleteNode(head, n//2)
return head
```
이번에는 `Linked List`를 홀/짝 인덱스에 따라 분리하는 문제였다. 추가 공간복잡도 O(1)과 시간복잡도 O(n)안에 해결하라는 챌린지 조건도 있었다.
문제를 해결하려면 결국 홀/짝 부분의 `Linked List`와, 짝 부분의 가장 앞의 위치를 알아야 하는데, 추가 공간복잡도 O(1)이라는 조건과 맞물려 머리가 아팠다. 주어진 조건이 변수보다는 주소 공간의 관점에서 O(1) 풀이를 말하는 것이지 않나 생각했다.
```python
class …
```
> [프로그래머스+LeetCode 75] [Seori] 25년 7주차 3문제 풀이

- Gombang/Programmers/표현 가능한 이진트리.cpp
- Gombang/[LeetCode75] - [Linked List]/206_Reverse_Linked_List.cpp
- Gombang/[LeetCode75] - [Linked List]/2130_Maximum_Twin_Sum_of_a_Linked_List.cpp
- 처음부터 순회를 하며 스택에 데이터를 모두 넣어준 후, 다시 꺼내면서 반대로 연결해주는 방식으로 진행.
- Meli님의 발표를 보고 간단하게 변수들만으로 역순으로 연결을 바꿀 수 있다는 것도 알게 되었다.
- 하나씩 순회를 진행하며 벡터에 데이터를 하나씩 담아주고, Twin으로 계산을 진행하여 최대값을 구하는 방식으로 진행.
- 이 문제도 그렇도 위의 문제도 그렇고 나는 링크드 리스트와 다른 자료구조를 합한 방식의 풀이었다면, Meli님의 풀이는 링크드 리스트의 특징을 활용하는 방식이었다. 머릿속으로 어떻게 하면 되지 않을까 싶은 풀이법을 볼 수 있어서 좋았다.
- 주어진 수를 이진수로 표현을 한 후, 이진수를 보고 이진트리가 될 수 있는지 아닌지에 대한 규칙을 찾아내는 문제였다. 알고리즘에 대해 여러가지 생각을 해보았지만 적절한 풀이법이 확 떠오르지 않아 빙빙 돌았던 문제.
- 처음에 생각했던 규칙은 '이진수를 보고 3개씩 끊으며 중간에 1이 들어가면 ok, 그렇지 않으면 no' 이렇게 단순하게 생각했다가 반례를 통해 틀린 생각이었다는 것을 알게 되었다.
- 두 번째로 생각했던 규칙은 '정중앙의 값은 반드시 1이어하고, 서브트리의 루트노드가 1이야 한다. 만약 정중앙 값이 0이지만 서브트리의 루트노드가 1인 경우가 있다면 안된다.' 이 방식으로 문제 풀이를 진행하였는데 절반만 정답이 되었다. 이 알고리즘을 회의 시간에 들고가니 루시님이 문제점을 찾아주셨다. 서브트리의 루트노드만 파악할 것이 아니라, 중앙값이 0이었을 때를 기준으로 왼쪽 모두, 오른쪽 모두를 보며 1인 값이 하나라도 있다면 false여야 …
> [프로그래머스+LeetCode 75] [Gombang] 25년 8주차 3문제 풀이

- Seori/LeetCode 75/Binary Tree_DFS/104. Maximum Depth of Binary Tree.py
- Seori/LeetCode 75/Binary Tree_DFS/872. Leaf-Similar Trees.py
- Seori/Programmers/표 병합.py
- Seori/TIL/25년 9주차 TIL.md
9주차 문제 유형은 이진트리의 `DFS`였다. 이진트리를 탐색하는 전위순회, 중위순회, 후위순회를 공부했고 구현이 가장 쉬운 전위순회로 문제를 해결했다.
```python
def maxDepth(self, root: Optional[TreeNode]) -> int:
def dfs(root: Optional[TreeNode], depth: int) -> int:
if root == None: 
return depth - 1
left = dfs(root.left, depth + 1)
right = dfs(root.right, depth + 1)
return max(left, right)
return dfs(root, 1)
```
이번 문제도 마찬가지로 전위순회로 해결했다. 주어지는 두 트리의 리프노드가 전위순회 순으로 탐색했을 때 같은지를 확인하는 문제였다.
```python
def leafSimilar(self, root1: Optional[TreeNode], root2: Optional[TreeNode]) -> bool:
def dfs(root: Optional[TreeNode], leaf_value_sequence: List) -> None:
if root == None: 
return
if root.left == None and root.right == None:
leaf_value_sequence.append(root.val)
left = dfs(root.left, leaf_value_sequence)
right = dfs(root.right, …
```
> [프로그래머스+LeetCode 75] [Seori] 25년 9주차 3문제 풀이

- Lucy/2025/3-W01/1448_Count_Good_Nodes_in_Binary_Tree.md
- Lucy/2025/3-W01/1448_Count_Good_Nodes_in_Binary_Tree.ts
- Lucy/2025/3-W01/437_Path_Sum_III.md
- Lucy/2025/3-W01/437_Path_Sum_III.ts
- Lucy/2025/3-W01/미로_탈출_명령어.md
- Lucy/2025/3-W01/미로_탈출_명령어_BFS사용.js
- Lucy/2025/3-W01/미로_탈출_명령어_모범답안_DFS.js
- 트리를 DFS로 순회하는 방식은 이해했으나 조금만 응용하는 문제가 나오면 주춤하게 된다. 다른 사람들의 아이디어를 보면 바로 코드가 떠오르는데 많이 풀어보는 수밖에 없는거 같다.
- 미로 탈출 명령어 문제는 처음에는 BFS로 S에서 E까지의 최단 경로를 구하고 k - minimumDistance 만큼 이동하는 방법을 생각해내면 되겠다고 생각하고 문제를 풀었는데 BFS로 풀면 시간초과로 답을 구해내지 못했다. 제한사항을 제대로 읽지 않아서 알고리즘 선택을 잘못했다. 가장 짧은 거리를 구하는 거는 BFS라고 생각하지 말고 문제를 제대로 읽어야 겠다고 생각했다.
> [프로그래머스+LeetCode 75] [Lucy] 25년 10주차 3문제 풀이

- Gombang/Programmers/미로 탈출 명령어.cpp
- Gombang/[LeetCode75] - [DFS]/1448_Count_Good_Nodes_in_Binary_Tree.cpp
- Gombang/[LeetCode75] - [DFS]/437_Path_Sum_III.cpp
- 해당 문제도 저번주와 마찬가지로 dfs방식을 이용하여, 큰 어려움 없이 풀이가 진행되었다.
- 트리에서 상위 노드에서 현재 노드까지 묶어서 나온 노드 값의 합과 주어진 TargetSum의 값과 동일한 path는 몇 개인지 구하는 문제였다. 벡터를 이용하여 depth가 하나씩 들어갈 때마다 벡터에 요소를 추가해주는 방식으로 진행해주었다.
- 해당 문제는 시작점으로부터 도착지점까지 주어진 k거리만큼 이동했을 때 나온 문자열 중, 사전 순서가 가장 빠른 문자열을 구하는 문제이다. 
- 처음에 생각했을 때는 시작점과 도착지점이라는 문장이 있어, 최단거리 알고리즘 문제일거라 생각했지만 중복으로 방문할 수 있다는 내용이 있어 이는 아니라고 생각했다.
- 다음으로 생각했던 것은 모든 조합을 다 찾아봐야되나싶어서 backtracking으로 모든 조합을 구하려고 했으나 k값이 2500이나 되어 경우의 수가 2^5000승이 나오게 되어 시간초과가 발생할거라 생각하여 진행하지 않았다.
- 마지막으로 문제에서 주어진 사전순으로 가장 빠른 문자열을 구하는 것이므로 이를 활용하기로 했다. 사전순으로 가장 빠른 것은 d->l->r->u 순이고 이 순서대로 문자열이 완성되면 바로 return하는 방식으로 진행하였다.
> [프로그래머스+LeetCode 75] [Gombang] 25년 10주차 3문제 풀이

- Seori/LeetCode 75/Binary Tree_DFS/1372. Longest ZigZag Path in a Binary Tree.py
- Seori/LeetCode 75/Binary Tree_DFS/236. Lowest Common Ancestor of a Binary Tree.py
- Seori/Programmers/행렬과 연산.py
- Seori/TIL/25년 11주차 TIL.md
이진트리의 `DFS` 완전탐색에서 조금 더 응용이 필요한 문제였다.
이 문제는 지그재그하면서 최대 깊이를 탐색하면서 동시에, 모든 노드가 지그재그의 시작점이 될 수 있었다. 분명 더 효율적인 백트래킹 풀이가 있을 것 같았지만… 이렇게 `DFS`를 활용해도 풀이에 성공했기 때문에 마무리했다.
```python
def longestZigZag(self, root: Optional[TreeNode]) -> int:
def dfs(root: Optional[TreeNode], direction: str, depth: int) -> int:
if root is None:
return depth
zigzag_path = 0
if direction == 'L': # 1. 왼쪽으로 들어온 경우, 오른쪽 및 시작점 탐색
zigzag_path = max(dfs(root.right, 'R', depth + 1), dfs(root.left, 'L', 0))
elif direction == 'R': # 2. 오른쪽으로 들어온 경우, 왼쪽 및 시작점 탐색
zigzag_path = max(dfs(root.left, 'L', depth + 1), dfs(root.right, 'R', 0))
else: # 3. 시작점인 경우, 왼쪽 및 오른쪽 탐색
zigzag_path = max(dfs(root.left, 'L', depth + 1), dfs(root.right, 'R', depth + 1))
return zigzag_path
return dfs(root, '', -1)
```
발상의 전환이 핵심이었던 …
> [프로그래머스+LeetCode 75] [Seori] 25년 11주차 3문제 풀이

- Lucy/2025/3-W03/1161_Maximum_Level_Sum_of_a_Binary_Tree.md
- Lucy/2025/3-W03/1161_Maximum_Level_Sum_of_a_Binary_Tree.ts
- Lucy/2025/3-W03/199_Binary_Tree_Right_Side_View.md
- Lucy/2025/3-W03/199_Binary_Tree_Right_Side_View.ts
- Lucy/2025/3-W03/등산코스_정하기.js
- Lucy/2025/3-W03/등산코스_정하기.md
- Lucy/2025/3-W03/등산코스_정하기_2.js
- Array.prototype.shift()는 O(n) 시간 복잡도가 소요된다.
- 다익스트라 알고리즘을 공부하는 계기가 됐다.
> [프로그래머스+LeetCode 75] [Lucy] 25년 12주차 3문제 풀이

- Meli/LeetCode 75/1161. Maximum Level Sum of a Binary Tree.py
- Meli/LeetCode 75/199_Binary_Tree_Right_Side_View.py
> [프로그래머스+LeetCode 75] [Meli] 25년 12주차 2문제 풀이

- Seori/LeetCode 75/Binary Tree_BFS/1161. Maximum Level Sum of a Binary Tree.py
- Seori/LeetCode 75/Binary Tree_BFS/199. Binary Tree Right Side View.py
- Seori/Programmers/등산코스 정하기.py
- Seori/TIL/25년 12주차 TIL.md
이진트리의 `BFS` 유형이 처음 등장했다. 난이도는 `Medium`이지만  `DFS`에서 넘어와 새 유형에 적응하기 좋은 문제였다.
깊이별로 `BFS` 탐색을 하면서 가장 오른쪽 노드만 남기는 방법을 구현하여 풀이했다.
```python
def rightSideView(self, root: Optional[TreeNode]) -> List[int]:
answer = []
if root is not None:
queue = [(root, 0)]
level = -1
while queue:
node, depth = queue.pop(0)
if depth > level:
answer.append(0)
level = depth
answer[depth] = node.val
if node.left is not None:
queue.append((node.left, depth + 1))
if node.right is not None:
queue.append((node.right, depth + 1))
return answer
```
이 문제는 고민이 조금 필요했다. 처음에는 위 문제와 같이 `queue`에 `root`와 `depth` 2개의 파라미터를 넣는 방법을 고안했지만 `depth`가 달라질 때의 처리가 명확하지 않아 코드가 복잡해졌고 속도도 느렸다. 어떻게든 문제를 해결한 뒤 모범답안을 참고했는데, `root` 1개의 파라미터만 사용하고 for 반복문을 활용하여 코드를 간단하게 만든 풀이가 이목을 끌었다.
`BFS` 문제에서 `pop()`은 항상 while문 최상위에서 해준다는 강박이 …
> [프로그래머스+LeetCode 75] [Seori] 25년 12주차 3문제 풀이

- Lucy/2025/3-W04/450_Delete_Node_in_a_BST.ts
- Lucy/2025/3-W04/700_Search_in_a_Binary_Search_Tree.ts
- Lucy/2025/3-W04/코딩_테스트_공부.js
- Lucy/2025/3-W04/코딩_테스트_공부_다익스트라.js
- Binary Search Tree 개념을 오랜만에 다시 공부하는 시간을 가졌다.
- DP는 규칙을 찾아내는 것이 어렵다.
- 코딩 테스트 공부 문제를 다익스트라 알고리즘으로 풀 수 있다기에 도전했는데 Chat GPT의 도움을 받아 겨우 풀었다.
> 2025 3 w04[프로그래머스+LeetCode 75] [Lucy] 25년 13주차 3문제 풀이

- Meli/LeetCode 75/450. Delete Node in a BST.py
- Meli/LeetCode 75/700. Search in a Binary Search Tree.py
- Meli/Programmers/2022_kakao_coding_test.py
- Meli/TIL/2025_03_27.md
- binary search tree 에 대한 복습을 하면서, 그 특성을 이용해 문제를 풀었다.
- 카카오 문제는 규칙을 찾아야 했는데, 그 부분에서 구현이 조금 어려웠다.
> [프로그래머스+LeetCode 75] [Meli] 25년 13주차 3문제 풀이

- Gombang/Programmers/사라지는발판.cpp
- Gombang/[LeetCode75] - [DFS]/547_Number_of_Provinces.cpp
- Gombang/[LeetCode75] - [DFS]/841_Keys_and_Rooms.cpp
- dfs를 활용하는 문제였다. 첫 번째 방문은 열려있기 때문에, 처음 방에 있는 열쇠를 통해 dfs로 순회하는 방식으로 풀이를 진행하였다.
- 예전에 한 번 알고리즘 스터디에서 풀었었던 문제였다. 알고리즘 스터디를 처음 했었던 당시에 풀었던 풀이방법을 다시 보니 그 당시에는 얼마나 이상하게 풀었었는지를 느낄 수 있었다...ㅎㅎ 예전의 풀이법은 전형적인 dfs풀이 방법이 아닌 dfs를 가장한 요상한 풀이방법으로 진행했다는 것을 알 수 있었다.
- 이 문제도 dfs를 활용하는 문제였다.
- visited라는 변수를 통해 방문 여부를 체크하며, 연결된 도시가 있는 경우 카운팅을 하지 않고 dfs로 순회하며 방문 여부만 체크하는 방식으로 진행하였다.
- 한 가지 재미있었던 점은 프로그래머스의 dfs유형에는 network라는 개념으로 이와 동일한 문제가 있었던 것이 떠올랐다.
( https://school.programmers.co.kr/learn/courses/30/lessons/43162 )
- 이 문제는 처음에 어떻게 풀어야 할 지 전혀 감이 잡히지 않아 해설 및 서리님의 발표를 보고 이해를 하게 되었다.
- 서리님의 발표를 확인해보니 서로 번갈아 가면서 최선의 경우로 완전탐색을 하는 방법이라는 것을 알게 되었다.
- 다른 풀이 법으로는 minimax알고리즘을 활용하는 방법이었다. 이 방식은 턴제의 게임에서 서로 최선의 방법을 선택하는 방식의 알고리즘이다. 이 풀이법의 핵심은 모든 턴을 서로의 입장에서 최선의 방법으로 카운팅 했을 때 짝수로 끝나게 된다면 내가 지는 것을 의미하고, 홀수로 끝나게 되면 내가 …
> [프로그래머스+LeetCode 75] [Gombang] 25년 14주차 3문제 풀이

- Lucy/2025/4-W03/1926_Nearest_Exit_from_Entrance_in_Maze.md
- Lucy/2025/4-W03/1926_Nearest_Exit_from_Entrance_in_Maze.ts
- Lucy/2025/4-W03/994_Rotting_Oranges.md
- Lucy/2025/4-W03/994_Rotting_Oranges.ts
- Lucy/2025/4-W03/양과_늑대.js
- Lucy/2025/4-W03/양과_늑대.md
- BFS로 최단 경로를 찾을 경우 가장 먼저 조건에 해당되는 목적지에 도달한 경우가 최단 경로라는걸 다시 학습할 수 있었다.
```typescript
function nearestExit(maze: string[][], entrance: number[]): number {
const queue: [number, number, number][] = [];
queue.push([entrance[0], entrance[1], 0]); // [row, col, path]
const ROW = maze.length;
const COL = maze[0].length;
const EMPTY = ".";
const direction = [
[1, 0],
[-1, 0],
[0, 1],
[0, -1],
];
const visited: boolean[][] = Array.from({ length: ROW }, () => new Array(COL).fill(false));
const getCoordinates = (row: number, col: number): string => `${row},${col}`;
while (queue.length > 0) {
const [row, col, currentPath] = queue.shift()!;
if (row === 0 || row === ROW - 1 || col === 0 || col === COL - 1) {
if (getCoordinates(row, col) !== getCoordinates(entrance[0], entrance[1])) {
return …
```
> [프로그래머스+LeetCode 75] [Lucy] 25년 16주차 3문제 풀이

- Gombang/Programmers/양궁대회.cpp
- Gombang/[LeetCode75] - [Priority_Queue]/215_Kth_Largest_Element_in_an_Array.cpp
- Gombang/[LeetCode75] - [Priority_Queue]/2336_Smallest_Number_in_Infinite_Set.cpp
- 해당 문제는 주어진 배열에서 정렬을 사용하지 않고 k번째로 큰 수를 찾아내는 문제였다. 우선순위 큐 문제라는 것을 알고있는 상태에서 진행하다보니 크게 막히지 않고 진행할 수 있었다. 
- 내가 진행했던 방법은 최대힙을 만들어서 모든 데이터를 다 집어 넣고 k-1번 pop을 진행하면 top에 있는 것이 k번째로 큰 수이다라는 방식으로 진행하였다. 이렇게 했을 경우 불필요한 연산이 진행되는 것이 눈에 보였고, 어떻게 하면 불필요한 연산을 줄일 수 있을지를 고민해보다가 모범 답안을 확인하게 되었다.
- 모범 답안에서는 최소 힙의 풀이법이었고, 최소힙의 크기를 k개를 유지하며 데이터를 넣게 되면 하위 노드들은 top보다 항상 큰 값이 들어갈 것이므로, nums에 대해서 한 번의 순회만으로 정답을 찾아낼 수 있었다.
- 이 문제는 클래스를 완성하는 문제였는데, 어떻게 접근해야 옳은것인지 명확하게 떠오르지 않아, 제한사항의 조건을 보고 1부터 1000까지의 데이터를 직접 unordered_set과 heap에 넣는 방식으로 진행하게 되었다. 이렇게 풀면서도 이상하게 푼다는 느낌을 받게 되었지만 마땅히 다른 방법이 떠오르지 않아 일단 정답을 맞춰보자는 식으로 처리하였다.
- 다른 답안을 확인해보니, `1부터 무한으로 양의 정수를 가지고 있다`는 의미를 간단하게 하나의 int변수를 통해서 관리하는 방식을 알게 되었다. 또한, cpp의 set은 레드 블랙 트리의 구조로 되어 있기에, 자동으로 오름차순 정렬을 처리해주고 있어서 이 자료구조를 사용한 것을 확인하게 되었다. 이러한 풀이를 보니 훨씬 깔끔하고 문제를 정확히 …
> [프로그래머스+LeetCode 75] [Gombang] 25년 17주차 3문제 풀이

- Lucy/2025/5-W02/2300_Successful_Pairs_of_Spells_and_Potions.ts
- Lucy/2025/5-W02/374_Guess_Number_Higher_or_Lower.ts
- Lucy/2025/5-W02/k진수에서_소수_개수_구하기.js
- 이진 탐색에 대해서 공부하는 시간을 갖게 됐다.
- 소수 관련된 문제를 오랜만에 풀어본다.
> [프로그래머스+LeetCode 75] [Lucy] 25년 19주차 3문제 풀이
